<?php
return array (
  'app_version' => '3.2.0',
  'web_version' => '3.2.0',
  'app_release_stamp' => '2026-05-08T21:25:21+04:00',
  'web_release_stamp' => '2026-05-08T21:25:21+04:00',
  'app_release_type' => 'feature',
  'web_release_type' => 'feature',
  'app_release_summary' => '',
  'web_release_summary' => '',
  'app_title' => 'Ծրագրի նոր տարբերակ',
  'app_message' => 'Ծրագիրը թարմացվել է։ Սեղմեք թարմացնել, որպեսզի օֆֆլայն և օնլայն բովանդակությունը նորացվի։',
  'web_title' => 'Կայքի նոր տարբերակ',
  'web_message' => 'Կայքը թարմացվել է։ Սեղմեք թարմացնել, որպեսզի բացվի նոր տարբերակը։',
  'maintenance_enabled' => false,
  'maintenance_message' => 'Կայքում ընթացքի մեջ են տեխնիկական աշխատանքներ։ Խնդրում ենք փորձել մի փոքր հետո։',
  'maintenance_start_at' => '',
  'maintenance_end_at' => '',
  'server_package_file' => '20260401-181623-update-security-sync-2026-04-01.zip',
  'server_package_mode' => 'partial',
  'server_package_uploaded_at' => '2026-04-01T18:16:23+04:00',
  'server_package_uploaded_by' => 'paruyr.movsesyan2005@gmail.com',
  'server_package_applied_at' => '2026-04-01T18:16:23+04:00',
  'server_package_applied_by' => 'paruyr.movsesyan2005@gmail.com',
  'server_package_last_backup' => '20260401-181623-f0fea1',
  'server_package_linked_app_version' => '3.0.5',
  'server_package_linked_web_version' => '3.0.5',
  'server_package_release_synced_at' => '2026-04-01T18:16:23+04:00',
  'admin_emails' => 
  array (
    0 => 'paruyr.movsesyan2005@gmail.com',
  ),
  'admin_user_permissions' => 
  array (
    'paruyr.movsesyan2005@gmail.com' => 
    array (
      'release' => true,
      'maintenance' => true,
      'push' => true,
      'devices' => true,
      'history' => true,
      'access' => true,
      'moderation' => true,
      'translations' => true,
      'songs_editor' => true,
    ),
  ),
  'social_auth_google_client_id' => '169805085378-f58dpr8rkp993ag9h8fu05idnocn4j6s.apps.googleusercontent.com',
  'social_auth_google_redirect_uri' => 'https://worship.pmstudio.am/social_auth.php?provider=google',
  'page_app_modes' => 
  array (
    'landing' => true,
    'main' => true,
    'song' => true,
    'favorites' => true,
    'setlists' => true,
    'account' => true,
    'news' => false,
    'auth' => true,
  ),
  'meta_note' => '',
  'updated_at' => '2026-05-08T21:25:21+04:00',
  'translation_enabled' => false,
  'translation_model' => 'gpt-4.1-mini',
  'social_auth_apple_client_id' => '',
  'social_auth_apple_team_id' => '',
  'social_auth_apple_key_id' => '',
  'social_auth_apple_redirect_uri' => '',
);
