import React, { createContext, useState, useContext, useEffect } from 'react';

const translations = {
  am: {
    auth: {
      loginTitle: 'Մուտք գործիր քո հաշվով',
      loginSubtitle: 'Մեկ միասնական մուտք քո անձնական գրադարանի, սեթլիստների և ծանուցումների համար՝ թե՛ կայքում, թե՛ ծրագրում։',
      back: 'Վերադառնալ',
      welcomeBack: 'Բարի վերադարձ',
      welcomeBackDesc: 'Մուտք գործիր, որպեսզի համաժամացնես քո պահպանված երգերը և սեթլիստները բոլոր սարքերում։',
      fillAllFields: 'Լրացրեք բոլոր դաշտերը',
      invalidLogin: 'Սխալ էլ. փոստ կամ գաղտնաբառ',
      invalidEmail: 'Մուտքագրեք վավեր էլ. փոստի հասցե',
      invalidUsernameSpaces: 'Մուտքանունը չի կարող բացատ պարունակել',
      networkError: 'Կապի խնդիր, խնդրում ենք փորձել կրկին:',
      saveLoginTitle: 'Պահպանե՞լ մուտքը այս սարքում',
      saveLoginDesc: 'Եթե պահպանեք մուտքը, այս սարքում նորից մուտք գործելու կարիք չի լինի, մինչև ինքներդ դուրս չգաք հաշվից։',
      saveLoginConfirm: 'Պահպանել մուտքը',
      saveLoginSkip: 'Ոչ հիմա',
      saveLoginError: 'Չհաջողվեց պահպանել մուտքը',
      loginOrEmail: 'Էլ. փոստ',
      password: 'Գաղտնաբառ',
      rememberMe: 'Հիշել ինձ',
      forgotPassword: 'Մոռացե՞լ եք',
      pleaseWait: 'Խնդրում ենք սպասել...',
      loginBtn: 'Մուտք',
      orContinue: 'կամ շարունակիր',
      googleLogin: 'Google-ով մուտք',
      googleReady: 'Պատրաստ է մուտքի համար',
      googleDisabled: 'Google մուտքը դեռ կարգավորված չէ։ Խնդրում ենք միացնել այն ադմինում։',
      googleDisabledShort: 'Դեռ կարգավորված չէ',
      noAccount: 'Չունե՞ս հաշիվ։',
      createNow: 'Ստեղծել հիմա',
      guestEyebrow: 'Քո երաժշտական աշխատանքային տարածքը',
      guestDescription: 'Բացիր երգերը, փոխիր տոնայնությունը և պահիր ամեն ինչ մեկ անվտանգ հաշվում։',
      guestPreviewLabel: 'Ակորդների նախադիտում',
      guestPreviewTitle: 'Պատրաստ է փորձին',
      guestKey: 'Տոն՝',
      guestOpenTransposer: 'Բացել տրանսպոզը',
      guestLogin: 'Մուտք գործել',
      guestBrowseSongs: 'Դիտել երգարանը որպես հյուր',
      registerTitle: 'Ստեղծել հաշիվ',
      registerSubtitle: 'Միացիր պաշտամունքային թիմերին ամբողջ աշխարհից։ Պահպանիր քո երգերը և սեթլիստները բոլոր սարքերում։',
      joinCommunity: 'Միացիր մեր համայնքին',
      joinDesc: 'Ստեղծիր անվճար հաշիվ՝ քո անձնական գրադարանը և թիմերը կառավարելու համար։',
      fullName: 'Անուն Ազգանուն',
      username: 'Մուտքանուն',
      email: 'Էլ. հասցե',
      confirmPassword: 'Հաստատել գաղտնաբառը',
      passwordMismatch: 'Գաղտնաբառերը չեն համընկնում',
      registerBtn: 'Գրանցվել',
      hasAccount: 'Արդեն ունե՞ս հաշիվ։',
      loginNow: 'Մուտք գործել'
    },
    settings: {
      title: 'Կարգավորումներ',
      mobileMenu: 'Մենյու',
      tabs: {
        profile: 'Անձնական',
        app: 'Ծրագիր',
        security: 'Անվտանգություն',
        sessions: 'Սեսիաներ',
        requests: 'Հարցումներ',
        about: 'Ծրագրի մասին',
        danger: 'Վտանգավոր'
      },
      app: {
        desc: 'Կարգավորեք ծրագրի արտաքին տեսքը և աշխատանքի պարամետրերը:',
        themeMode: 'Գունային ռեժիմ',
        themeModeDesc: 'Ընտրեք ծրագրի բաց կամ մութ տեսքը։',
        darkTheme: 'Մութ',
        lightTheme: 'Բաց',
        keepAwake: 'Միշտ արթուն էկրան',
        keepAwakeDesc: 'Երգերի բառերը կարդալիս էկրանը չի անջատվի։',
        reduceMotion: 'Պարզեցված անիմացիաներ',
        reduceMotionDesc: 'Անջատում է էջերի անցումների էֆեկտները ավելի արագ աշխատանքի համար։',
        oledMode: 'OLED Մութ ռեժիմ (Իրական սև)',
        oledModeDesc: 'Օգտագործում է բացարձակ սև գույնը (OLED էկրանների համար՝ մարտկոց խնայելու նպատակով)։',
        oledDarkOnly: 'Հասանելի է միայն մութ ռեժիմում։',
        outlinedChords: 'Շրջանակված ակորդներ',
        outlinedChordsDesc: 'Ակորդները ցուցադրվում են որպես առանձին կոճակներ՝ ավելի հեշտ կարդալու համար։',
        chordColor: 'Ակորդների գույն',
        chordStyle: 'Ակորդների ոճ',
        standardChords: 'Ստանդարտ',
        colorGold: 'Ոսկեգույն',
        colorBlue: 'Կապույտ',
        colorGreen: 'Կանաչ',
        colorRed: 'Կարմիր',
        colorWhite: 'Սպիտակ',
        colorBlack: 'Սև',
        enabled: 'Միացված է',
        disabled: 'Անջատված է',
        enable: 'Միացնել',
        disable: 'Անջատել',
        saved: 'Պահպանված է'
      },
      about: {
        tagline: 'Երգեր, ակորդներ և թիմային համագործակցություն մեկ ծրագրում։',
        version: 'Ծրագրի տարբերակ',
        status: 'Ծրագրի կարգավիճակ',
        statusActive: 'Ակտիվ (Անխափան)',
        statusMaintenance: 'Տեխնիկական սպասարկում',
        statusScheduled: 'Պլանավորված սպասարկում',
        platform: 'Տեղադրման տեսակ',
        offline: 'Օֆֆլայն աշխատանք',
        available: 'Հասանելի է',
        releaseType: 'Թողարկման տեսակ',
        releaseTypes: {
          major: 'Մեծ թարմացում',
          feature: 'Նոր հնարավորություն',
          patch: 'Փոքր ուղղում',
          hotfix: 'Արագ շտկում',
          maintenance: 'Տեխնիկական թարմացում',
          content: 'Բովանդակության թարմացում'
        },
        updated: 'Վերջին թարմացում',
        licenseTitle: 'Լիցենզիաներ',
        licenseText: 'Worship Platform-ը PM Studio-ի սեփական ծրագրային ապահովումն է։ Օգտագործված բաց կոդով գրադարանները տարածվում են իրենց համապատասխան լիցենզիաներով։',
        privacy: 'Գաղտնիություն',
        terms: 'Պայմաններ',
        support: 'Աջակցություն',
        rights: 'Բոլոր իրավունքները պաշտպանված են։'
      },
      profile: {
        title: 'Անձնական տվյալներ',
        desc: 'Խմբագրեք Ձեր հիմնական տվյալները։',
        name: 'Անուն Ազգանուն',
        birthDate: 'Ծննդյան ամսաթիվ',
        gender: 'Սեռ',
        genderMale: 'Արական',
        genderFemale: 'Իգական',
        genderOther: 'Այլ',
        phone: 'Հեռախոս',
        save: 'Պահպանել',
        success: 'Տվյալները թարմացվել են'
      },
      security: {
        title: 'Անվտանգություն և Մուտք',
        desc: 'Կառավարեք Ձեր գաղտնաբառը և էլ. փոստի հասցեն։',
        emailStatus: 'Էլ. փոստի կարգավիճակ',
        unverified: 'Չհաստատված',
        verified: 'Հաստատված',
        sendVerify: 'Ուղարկել հաստատման նամակ',
        changeEmail: 'Փոխել էլ. հասցեն',
        newEmail: 'Նոր էլ. հասցե',
        saveEmail: 'Պահպանել էլ. հասցեն',
        changePassword: 'Փոխել գաղտնաբառը',
        oldPassword: 'Ընթացիկ գաղտնաբառ',
        newPassword: 'Նոր գաղտնաբառ',
        savePassword: 'Փոխել գաղտնաբառը',
        forgotPassword: 'Մոռացել եմ գաղտնաբառը',
        emailSent: 'Հաստատման հղումն ուղարկված է',
        passChanged: 'Գաղտնաբառը հաջողությամբ փոխվեց'
      },
      sessions: {
        title: 'Ակտիվ սեսիաներ',
        desc: 'Այստեղ երևում են սարքերը, որտեղ բացված է քո հաշիվը։',
        closeOther: 'Փակել մյուսները',
        currentDevice: 'Ընթացիկ սարք',
        remembered: 'Հիշված սարք',
        rememberTitle: 'Հիշել ինձ այս սարքում',
        rememberEnabled: 'Միացված է',
        rememberDisabled: 'Անջատված է',
        rememberDescOn: 'Այս սարքում մուտքը պահպանված է և կմնա ակտիվ մինչև դուրս գաք հաշվից։',
        rememberDescOff: 'Եթե միացնեք, այս սարքում մուտքը պահպանված կմնա մինչև դուրս գաք հաշվից։',
        rememberEnableBtn: 'Միացնել',
        rememberDisableBtn: 'Անջատել',
        rememberUpdatedOn: 'Հիշել ինձ-ը միացվեց',
        rememberUpdatedOff: 'Հիշել ինձ-ը անջատվեց',
        logout: 'Դուրս գալ',
        empty: 'Սեսիաներ չեն գտնվել:'
      },
      requests: {
        title: 'Իմ ուղարկած հարցումները',
        desc: 'Նոր երգերի ավելացման կամ գոյություն ունեցող երգերում խմբագրումների հարցումների կարգավիճակը։',
        type: 'Տեսակը',
        date: 'Ամսաթիվ',
        adminNote: 'Ադմինի արձագանք',
        empty: 'Դուք դեռ չունեք ուղարկված հարցումներ։'
      },
      danger: {
        title: 'Վտանգավոր գործողություն',
        desc: 'Օգտահաշվի ջնջումը անշրջելի է։ Կկորչեն պահպանած երգերը և ամբողջ տվյալները։',
        deleteBtn: 'Ջնջել օգտահաշիվը',
        modalTitle: 'Հաստատեք ջնջումը',
        modalDesc: 'Խնդրում ենք մուտքագրել Ձեր գաղտնաբառը՝ հաշիվը վերջնականապես ջնջելու համար։',
        password: 'Գաղտնաբառ',
        cancel: 'Չեղարկել',
        confirm: 'Հաստատել և Ջնջել'
      }
    },
    dashboard: {
      library: 'Երգարան',
      search: 'Որոնել երգ...',
      loginSetlists: 'Մուտք գործեք երգացանկեր...',
      manageSetlists: 'Կառավարել երգացանկերը',
      loginPrompt: 'Մուտք գործեք՝ երգացանկեր կազմելու համար',
      loginBtn: 'Մուտք',
      emptySetlist: 'Այս երգացանկում դեռ երգեր չկան:',
      key: 'Տոնայնություն:',
      openStageReader: 'Բացել Stage Reader',
      emptyTitle: 'Հոգով և սրտով, զորությամբ Քեզ կերգեմ',
      emptyVerse: 'Verse/Chorus',
      emptyBridge: 'Bridge'
    },
    nav: {
      home: 'Գլխավոր',
      songs: 'Երգեր',
      transposer: 'Տրանսպոզ',
      sets: 'Երգացանկեր',
      friends: 'Ընկերներ',
      community: 'Համայնք',
      pricing: 'Գներ',
      resources: 'Ռեսուրսներ',
      news: 'Նորություններ',
      login: 'Մուտք',
      register: 'Գրանցվել',
      logout: 'Դուրս գալ',
      refresh: 'Թարմացնել',
      refreshing: 'Թարմացվում է…',
      retry: 'Փորձել նորից',
      retryOnline: 'Ինտերնետը դեռ հասանելի չէ։ Միացրեք կապը և նորից փորձեք։',
      online: 'Առցանց',
      offline: 'Օֆֆլայն',
      search: 'Որոնել...',
      setlists: 'Երգացանկեր'
    },
    megaMenu: {
      features: 'Հնարավորություններ',
      music: 'Երաժշտություն',
      management: 'Կառավարում',
      latestArrival: 'Նորություններ',
      discoverSongs: 'Բացահայտեք նոր երգեր, ակորդներ և ստեղծեք երգացանկեր:',
      readArticle: 'Կարդալ ավելին »',
      communityDesc: 'Միացեք մեր համայնքին, կիսվեք փորձով և գտեք նոր ընկերներ:',
      joinNow: 'Միանալ հիմա »',
      materials: 'Նյութեր',
      info: 'Տեղեկատվություն',
      contacts: 'Կապ'
    },
    landing: {
      heroTitle1: 'Առաջնորդի՛ր Պաշտամունքը',
      heroTitle2: 'Մեկ Միասնական Հարթակում',
      heroSubtitle: 'Ակորդներ, երգացանկեր և թիմային համագործակցություն — ամեն ինչ մեկ հարթակում։',
      startBtn: 'Սկսել անվճար',
      watchDemo: 'Դիտել Demo',
      popularSongs: 'Հայտնի Երգեր',
      communityPicks: 'Համայնքի Ընտրություն',
      browse: 'Թերթել',
      browseSongs: 'Երգեր',
      browseArtists: 'Արտիստներ',
      browseCollections: 'Հավաքածուներ',
      browseByKey: 'Ըստ տոնայնության',
      browseByBPM: 'Ըստ տեմպի',
      heroSubtitle1: 'Ավելի խելացի',
      latestNews: 'Վերջին Նորություններ',
      footerRights: '© 2026 Worship Platform. Բոլոր իրավունքները պաշտպանված են:',
      unknownArtist: 'Անհայտ արտիստ',
      picks: [
        { title: 'Երախտագիտություն', artist: 'Բրենդոն Լեյք', meta: 'Երգացանկ 14 · 9380 դիտում' },
        { title: 'Գերեզմաններից Պարտեզներ', artist: 'Bethel Worship', meta: 'Երգացանկ 17 · 320 դիտում' },
        { title: 'Ճանապարհ Բացող', artist: 'Sinach', meta: 'Երգացանկ 22 · 15k դիտում' }
      ],
      newsItems: [
        { date: 'Ապր 12, 2024', title: 'Նոր Հնարավորություն՝ Դինամիկ Տոնայնություն:', desc: 'Այժմ կարող եք փոխել երգի տոնայնությունը մեկ քլիքով:' },
        { date: 'Ապր 28, 2024', title: 'Տիրապետեք Երգացանկերի Պլանավորմանը', desc: 'Բացահայտեք, թե ինչպես է մեր գործիքը օգնում պլանավորել ծառայությունը:' },
        { date: 'Մայ 18, 2024', title: 'Համագործակցեք Ձեր Թիմի Հետ', desc: 'Կիսվեք ակորդներով և նշումներով Ձեր թիմի յուրաքանչյուր անդամի հետ:' }
      ],
      footer: {
        product: 'Պրոդուկտ',
        company: 'Ընկերություն',
        resources: 'Ռեսուրսներ',
        legal: 'Իրավական',
        songs: 'Երգեր',
        teams: 'Թիմ',
        pricing: 'Գներ',
        setlists: 'Երգացանկեր',
        about: 'Մեր մասին',
        blog: 'Բլոգ',
        careers: 'Կարիերա',
        community: 'Համայնք',
        documentation: 'Փաստաթղթեր',
        tutorials: 'Ուսուցում',
        support: 'Աջակցություն',
        privacyPolicy: 'Գաղտնիության քաղաքականություն',
        terms: 'Պայմաններ',
        cookies: 'Քուքիներ'
      }
    },
    songs: {
      title: 'Երգարան',
      search: 'Որոնել երգեր, հեղինակներ...',
      tableTitle: 'Անվանում',
      tableKey: 'Տոն.',
      tableBpm: 'BPM',
      tableAuthor: 'Հեղինակ',
      tableAdded: 'Ավելացված',
      openReader: 'Բացել',
      noResults: 'Ոչ մի արդյունք չի գտնվել',
      loading: 'Բեռնվում է...',
      loadMore: 'Ավելին',
      backToTop: 'Բարձրանալ վերև',
      sortTitle: 'Կարգ. Անուն',
      sortBpm: 'Կարգ. BPM',
      sortKey: 'Կարգ. Տոն.',
      sortRecent: 'Վերջին ավելացվածը',
      unknownArtist: 'Անհայտ արտիստ',
      removeFromFav: 'Հեռացնել',
      addToFav: 'Պահպանել',
    },
    songView: {
      added: 'Երգը պահպանվեց ♥',
      removed: 'Երգը հեռացվեց պահպանվածներից',
      loading: 'Բեռնվում է...',
      error: 'Չհաջողվեց բեռնել երգի տվյալները',
      back: 'Հետ գնալ',
      useFlats: 'b',
      transpose: 'Տոնայնություն',
      capoSub: 'Կապո',
      fontSize: 'Տառաչափ',
      downloadTxt: 'Ներբեռնել TXT',
      requestEdit: 'Խմբագրել',
      chordsOnly: 'Ակորդներ',
      lyricsOnly: 'Բառեր',
      bothModes: 'Երկուսն էլ',
      noCapo: 'Առանց Capo',
      clear: 'Ջնջել',
      keyPrefix: 'Տոն:',
      playAs: 'Նվագել որպես:',
      keySavedAlert: 'Տոնայնությունը պահպանվեց',
      keyIsSaved: '✓ Պահպանված է',
      saveKey: 'Պահպանել նոր տոնայնությունը',
      semitones: 'կիսատոն',
      reset: 'Reset',
      flats: '♭ Flats',
      sharps: '♯ Sharps',
      signs: 'Նշաններ',
      signs: 'Նշաններ',
      noLyrics: 'Բառերը հասանելի չեն',
      linkCopied: 'Հղումը պատճենված է',
      linkCopyError: 'Չհաջողվեց պատճենել հղումը',
      setlistTitle: 'Երգացանկ',
      key: 'Տոնայնություն:',
      tempo: 'Տեմպ:',
      addToSetlist: 'Ավելացնել երգացանկում',
      download: 'Ներբեռնել',
      edit: 'Խմբագրել',
      copied: 'Պատճենված է',
      copyError: 'Սխալ պատճենման ժամանակ',
      copyContent: 'Պատճենել երգը',
      copyLink: 'Պատճենել հղումը'
    },
    songRequest: {
      title: 'Երգի հարցում',
      titleNew: 'Առաջարկել Նոր Երգ',
      titleEdit: 'Խմբագրել երգը',
      badgeNew: '✨ Նոր Երգի Առաջարկ',
      badgeEdit: '✏️ Խմբագրման Առաջարկ',
      modeQuick: '⚡ Արագ Հարցում',
      modeFull: '🎼 Ամբողջական Տվյալներ',
      quickHint: 'Գրեք երգի վերնագիրը, հեղինակին կամ YouTube / MP3 հղումը։ Մեր թիմը կգտնի երգը, կտրանսպոզավորի ակորդները և կավելացնի։',
      quickTitlePlaceholder: 'Օրինակ՝ Օրհնիր Տեր կամ Hillsong - Oceans',
      quickNotesPlaceholder: 'Տեղադրեք YouTube / MP3 հղում կամ նշումներ (օրինակ՝ "Խնդրում եմ ավելացնել G տոնայնությամբ")...',
      needLogin: 'Հարցում ուղարկելու համար նախ մուտք գործիր։',
      songDataLoadError: 'Չհաջողվեց բեռնել երգի տվյալները',
      titleHy: 'Վերնագիր (Հայերեն)',
      titleLat: 'Վերնագիր (Լատինատառ)',
      titleEn: 'Վերնագիր (Անգլերեն)',
      titleRu: 'Վերնագիր (Ռուսերեն)',
      artist: 'Հեղինակ / Խումբ',
      songKey: 'Տոնայնություն',
      selectKeyPlaceholder: '-- Ընտրել Տոնայնությունը --',
      bpm: 'BPM (Տեմպ)',
      tags: 'Թեգեր',
      chords: 'Ակորդներ (ստանդարտ ֆորմատով)',
      lyrics: 'Բառեր (առանց ակորդների)',
      lyricsAndChordsSection: 'Ակորդներ և Տեքստ',
      chordsPreview: 'Ակորդների Նախադիտում',
      preview: '👁️ Նախադիտում',
      edit: '✏️ Խմբագրել',
      message: 'Նշում մոդերատորին (ոչ պարտադիր)',
      notesPlaceholder: 'Գրեք լրացուցիչ նշումներ կամ մեկնաբանություններ մոդերատորների համար...',
      basicsSection: 'Հիմնական Տվյալներ',
      musicSection: 'Երաժշտական Մանրամասներ',
      submit: 'Ուղարկել',
      submitBtnNew: 'Ուղարկել Առաջարկը',
      submitBtnEdit: 'Պահպանել & Ուղարկել Խմբագրումը',
      submitting: 'Ուղարկվում է...',
      success: 'Հարցումը հաջողությամբ ուղարկվեց:',
      submitError: 'Չհաջողվեց ուղարկել հարցումը',
      networkError: 'Կապի խնդիր',
      backToSong: 'Վերադառնալ երգին'
    },
    setlists: {
      heroTitle: 'Պաշտամունքի Ծրագրեր',
      heroSubtitle: 'Կառավարեք ձեր երգացանկերը, պլանավորեք ծառայությունները և կիսվեք թիմի հետ:',
      statTotalSets: 'Երգացանկեր',
      statTotalSongs: 'Ընդհանուր երգեր',
      statTeamSets: 'Թիմային',
      tabAll: 'Բոլորը',
      tabPersonal: 'Անձնական',
      tabTeam: 'Թիմային',
      tabShared: 'Կիսված',
      sortNewest: 'Նորերը սկզբում',
      sortOldest: 'Հիները սկզբում',
      sortName: 'Ըստ անվան',
      sortItems: 'Ըստ երգերի քանակի',
      noDate: 'Առանց ամսաթվի',
      backToSetlists: 'Երգացանկեր',
      publicBadge: 'Հանրային Երգացանկ',
      liveMode: 'Live Ռեժիմ',
      saveToAccount: 'Պահպանել իմ հաշվում',
      copyLink: 'Պատճենել հղումը',
      copied: 'Պատճենված է!',
      saving: 'Պահպանվում է...',
      statItems: 'Տարրեր',
      statSongs: 'Երգեր',
      statSections: 'Բաժիններ',
      statRequired: 'Պարտադիր',
      itemsTitle: 'Երգացանկի Երգեր',
      keyLabel: 'Տոն',
      required: 'Պարտադիր',
      section: 'Բաժին',
      errorTitle: 'Երգացանկը հասանելի չէ',
      invalidToken: 'Անվավեր կամ բացակայող հղում։',
      allSetlists: 'Դիտել Երգացանկերը',
      importedTag: 'Պատճեն',
      loginPrompt: 'Խնդրում ենք մուտք գործել՝ երգացանկեր կազմելու համար։',
      newSetlist: 'Նոր Երգացանկ',
      errorLoad: 'Չհաջողվեց բեռնել երգացանկերը',
      colTitle: 'Անվանում',
      colDate: 'Ամսաթիվ',
      colSongs: 'Երգեր',
      colType: 'Տեսակ',
      loading: 'Բեռնվում է...',
      empty: 'Դուք չունեք պահպանված երգացանկեր',
      unknownDate: 'Անհայտ',
      songsCount: 'երգ',
      typeShared: 'Համատեղ',
      typePersonal: 'Անձնական',
      edit: 'Խմբագրել',
      errorFetch: 'Չհաջողվեց բեռնել երգացանկի տվյալները',
      goBack: 'Հետ գնալ',
      addSong: 'Ավելացնել երգ',
      closeSearch: 'Փակել փնտրումը',
      searchPlaceholder: 'Փնտրել երգ ավելացնելու համար...',
      searchBtn: 'Փնտրել',
      addBtn: 'Ավելացնել',
      emptySetlist: 'Երգացանկը դատարկ է։ Ավելացրեք երգեր փնտրման միջոցով։',
      noKey: 'Չկա',
      remove: 'Հեռացնել',
      confirmRemove: 'Համոզվա՞ծ եք, որ ուզում եք հեռացնել:',
      errorOccurred: 'Սխալ տեղի ունեցավ',
      searchResults: 'Որոնման արդյունքները',
      editSetlist: 'Խմբագրել երգացանկը',
      nameField: 'Անուն',
      dateField: 'Ամսաթիվ / Օր',
      descField: 'Նկարագրություն',
      cancelBtn: 'Չեղարկել',
      saveBtn: 'Պահպանել',
      savingBtn: 'Պահպանվում է...',
      namePlaceholder: 'օր․ Կիրակնօրյա Պաշտամունք',
      assignTeam: 'Կցել թիմին (ոչ պարտադիր)',
      personalTeam: '-- Անձնական --',
      createBtn: 'Ստեղծել',
      creatingBtn: 'Ստեղծվում է...',
      deleteBtn: 'Ջնջել Երգացանկը',
      confirmDelete: 'Համոզվա՞ծ եք, որ ցանկանում եք ջնջել այս երգացանկը։ Այս գործողությունը անդառնալի է:',
      limitReached: 'Երգացանկերի սահմանափակումը սպառվել է:',
      createFailed: 'Չհաջողվեց ստեղծել երգացանկ:',
      networkError: 'Կապի խնդիր'
    },
    news: { 
      title: 'Նորություններ և Թարմացումներ'
    },
    teams: {
      hero: 'Ղեկավարի՛ր Քո Թիմը Վստահությամբ',
      badge: 'Պաշտամունքային Ղեկավարների համար',
      subtitle: 'Ամեն ինչ, ինչ անհրաժեշտ է քո պաշտամունքային թիմը համակարգելու համար՝ մեկ հզոր, հեշտ օգտագործվող հարթակում:',
      cta: 'Տեսնել Գները',
      ctaJoin: 'Սկսել Անվճար',
      dashboard: 'Գնալ Վահանակ',
      featuresTitle: 'Այն Ամենը, Ինչ Քո Թիմին Անհրաժեշտ Է',
      ctaTitle: 'Պատրա՞ստ ես զինել քո թիմը:',
      ctaSub: 'Միացիր հազարավոր պաշտամունքային թիմերին, ովքեր արդեն օգտագործում են Worship Platform-ը:',
      newTeamNamePrompt: 'Նոր թիմի անուն:',
      memberEmailPrompt: 'Մասնակցի էլ. հասցե:',
      addedAlert: 'Ավելացվեց',
      createNewTeamBtn: 'Ստեղծել նոր թիմ',
      upgradeRequired: 'Անհրաժեշտ է փաթեթի բարելավում',
      cancelBtn: 'Չեղարկել',
      seePlansBtn: 'Տեսնել Գները',
      noTeams: 'Դուք դեռ թիմեր չունեք:',
      membersCountLabel: 'անդամ',
      roles: ['Կիթառահար', 'Դաշնակահար', 'Թմբկահար', 'Վոկալիստ', 'Փողային'],
      featuresList: [
        { icon: '👥', title: 'Թիմի Անդամներ', desc: 'Ավելացրու երաժիշտներ և վոկալիստներ: Կառավարիր դերերն ու իրավունքները:' },
        { icon: '📋', title: 'Համատեղ Երգացանկեր', desc: 'Ստեղծիր և կիսվիր երգացանկերով թիմի հետ իրական ժամանակում:' },
        { icon: '🎵', title: 'Ակորդներ', desc: 'Տրամադրիր թիմին ակորդների և բառերի հասանելիություն:' },
        { icon: '🔔', title: 'Փորձերի Ծանուցումներ', desc: 'Ուղարկիր ավտոմատ հիշեցումներ փորձերի համար:' },
        { icon: '📊', title: 'Վիճակագրություն', desc: 'Տես, թե որ երգերն են ամենաշատը օգտագործվում և հետևիր ակտիվությանը:' },
        { icon: '💬', title: 'Թիմային Չաթ', desc: 'Շփվիր անմիջապես հարթակի ներսում: Նոր հավելվածներ պետք չեն:' }
      ],
      addMemberPrompt: 'Մուտքագրեք նոր անդամի էլ. հասցեն:',
      confirmRemoveMember: 'Համոզվա՞ծ եք:',
      confirmDeleteTeam: 'Համոզվա՞ծ եք, որ ուզում եք ջնջել այս թիմը:',
      teamDetails: 'Թիմի տվյալներ',
      deleteTeamBtn: 'Ջնջել Թիմը',
      addMemberBtn: '+ Ավելացնել Անդամ',
      teamMembersListTitle: 'Թիմի Անդամներ',
      noMembers: 'Այս թիմում դեռ անդամներ չկան:'
    },
    favorites: {
      errorLoad: 'Չհաջողվեց բեռնել պահպանված երգերը',
      loginTitle: 'Մուտք գործեք',
      loginPrompt: 'Խնդրում ենք մուտք գործել՝ ձեր պահպանված երգերը տեսնելու համար:',
      loginBtn: 'Մուտք',
      title: 'Պահպանված երգեր',
      savedSongs: 'պահպանված երգեր',
      loading: 'Բեռնվում է...',
      favoriteTag: 'Պահպանված',
      playlist: 'Պլեյլիստ',
      confirmRemove: 'Հեռացնե՞լ երգը պահպանվածներից:',
      keyTag: 'Տոնայնություն:',
      openSong: 'Բացել Երգը',
      noFavorites: 'Դեռ չունեք պահպանված երգեր:',
      emptyDesc: 'Պահպանված երգերը կհայտնվեն այստեղ, որպեսզի արագ վերադառնաք դրանց։',
      openFirst: 'Բացել առաջին երգը',
      browseSongs: 'Բացել երգարանը',
      viewAll: 'Տեսնել բոլորը',
      retry: 'Կրկին փորձել',
      filterAll: 'Բոլորը',
      filterAndSort: 'Ֆիլտր և դասակարգում',
      keyFilter: 'Տոնայնություն',
      resetFilters: 'Մաքրել',
      applyFilters: 'Կիրառել',
      sortLabel: 'Դասակարգել',
      sortSavedNewest: 'Վերջին պահպանվածները',
      sortSavedOldest: 'Առաջին պահպանվածները',
      sortTitle: 'Վերնագիր՝ Ա-Ֆ',
      sortArtist: 'Կատարող՝ Ա-Ֆ',
      sortKey: 'Տոնայնություն',
      sortBpmAsc: 'BPM՝ ցածրից բարձր',
      sortBpmDesc: 'BPM՝ բարձրից ցածր',
      noFilterResults: 'Այս ֆիլտրով երգ չի գտնվել',
      noFilterResultsDesc: 'Փորձեք ընտրել այլ տոնայնություն կամ բացել բոլոր պահպանված երգերը։',
      filterReset: 'Ցույց տալ բոլորը'
    },
    notifications: {
      title: 'Ծանուցումներ',
      markAllRead: 'Նշել որպես կարդացված',
      loading: 'Բեռնվում է...',
      newNotification: 'Նոր ծանուցում',
      emptyTitle: 'Նոր ծանուցումներ չկան',
      emptyDesc: 'Այստեղ կհայտնվեն Ձեր թիմի, երգացանկերի և այլ կարևոր իրադարձությունների մասին ծանուցումները:'
    },
    pricing: {
      badge: 'Պարզ Գներ',
      title: 'Պլաններ Բոլոր Թիմերի Համար',
      subtitle: 'Սկսիր անվճար: Ընդլայնիր, երբ Քո ծառայությունն աճի:',
      faqTitle: 'Հաճախ Տրվող Հարցեր',
      popular: 'Ամենապահանջված'
    },
    community: {
      title: 'Համայնքային Ֆորում',
      subtitle: 'Կապ հաստատիր աշխարհի տարբեր երկրների պաշտամունքային ղեկավարների հետ:',
      trending: '🔥 Թրենդային Թեմաներ',
      resources: '📌 Ռեսուրսներ',
      browseLibrary: '🎵 Թերթել Երգարանը',
      createSetlist: '📋 Ստեղծել Երգացանկ',
      latestNews: '📰 Վերջին Նորությունները',
      replies: 'պատասխան',
      share: 'Կիսվել'
    },
    resources: {
      title: 'Ռեսուրսներ',
      subtitle: 'Ուղեցույցներ, ձեռնարկներ և գործիքներ քո թիմի հաջողության համար:',
      search: 'Որոնել ռեսուրսներ...'
    },

    profile: {
      title: 'Պրոֆիլ',
      desc: 'Կառավարեք Ձեր հաշիվը և նախընտրությունները:',
      currentPlan: 'Ընթացիկ փաթեթ',
      loading: 'Բեռնվում է...',
      upgradePlan: 'Փոխել փաթեթը',
      savedSongs: 'Պահպանված երգեր',
      myTeams: 'Իմ թիմերը',
      accountSettings: 'Կարգավորումներ',
      language: 'Լեզու',
      logout: 'Ելք',
      selectLanguage: 'Ընտրեք լեզուն',
      pushOn: 'Միացված է։ Չաթի նոր նամակները կստանաք ժամանակին։',
      pushOff: 'Միացրեք, որպեսզի չաթից նոր նամակները բաց չթողնեք։',
      pushNote: 'Եթե ծանուցումները միացված չեն, չաթից նոր նամակներ չեք ստանա։ Ծրագրի համար սա պարտադիր է։',
      pushMissingManager: 'Սխալ առաջացավ ծանուցումների ակտիվացման ժամանակ։',
      pushDisableConfirm: 'Եթե ծանուցումները անջատեք, չաթից նոր նամակներ չեք ստանա։ Վստա՞հ եք, որ ուզում եք անջատել։',
      pushNotSupported: 'Ձեր սարքը կամ բրաուզերը չի ապահովում Push ծանուցումներ: Համոզվեք, որ ծրագիրը ավելացրել եք հեռախոսի էկրանին։',
      pushEnableError: 'Ծանուցումները մերժվեցին կամ խնդիր առաջացավ։'
    },
    friends: {
      confirmRemove: 'Համոզվա՞ծ եք։',
      tabs: {
        chats: 'Չաթեր',
        myFriends: 'Իմ ընկերները',
        add: 'Ավելացնել',
        requests: 'Հարցումներ'
      },
      emptyFriends: 'Դուք դեռ ընկերներ չունեք: Անցեք «Ավելացնել» բաժին նոր ընկերներ գտնելու համար:',
      chat: 'Չաթ',
      remove: 'Հեռացնել',
      findTitle: 'Գտնել ընկերներ',
      findDesc: 'Որոնեք օգտատերերին ըստ անվան կամ էլ. փոստի',
      searchPlaceholder: 'Մուտքագրեք անուն կամ փոստ...',
      alreadyFriends: 'Ընկերներ եք (Չաթ)',
      cancelRequest: 'Չեղարկել հարցումը',
      acceptRequest: 'Ընդունել հարցումը',
      addFriend: '+ Ավելացնել',
      searchEmpty: 'Ոչինչ չգտնվեց «{{query}}» որոնմամբ:',
      incomingTitle: 'Ստացված հարցումներ',
      outgoingTitle: 'Ուղարկված հարցումներ',
      noIncoming: 'Դուք չունեք նոր հարցումներ:',
      noOutgoing: 'Դուք սպասվող ուղարկված հարցումներ չունեք:',
      accept: 'Ընդունել',
      reject: 'Մերժել',
      cancel: 'Չեղարկել'
    },
    chat: {
      today: 'Այսօր',
      yesterday: 'Երեկ',
      monthsGenitive: ['հունվարի', 'փետրվարի', 'մարտի', 'ապրիլի', 'մայիսի', 'հունիսի', 'հուլիսի', 'օգոստոսի', 'սեպտեմբերի', 'հոկտեմբերի', 'նոյեմբերի', 'դեկտեմբերի'],
      deletedOrUnavailable: 'Այս զրույցը ջնջվել է կամ հասանելի չէ:',
      group: 'Խումբ',
      offline: 'Անցանց',
      online: 'Առցանց',
      lastSeen: 'Վերջին անգամ՝',
      friendFallback: 'Ընկեր',
      chatFallback: 'Չաթ',
      deleteTooltip: 'Ջնջել զրույցը',
      loadingOlder: 'Ավելի հին հաղորդագրությունները բեռնվում են...',
      emptyTitle: 'Սկսեք զրույցը',
      emptySubtitle: 'Գրեք առաջին հաղորդագրությունը այստեղ...',
      placeholder: 'Գրեք հաղորդագրություն...',
      sent: 'Ուղարկված է',
      seen: 'Տեսել է',
      key: 'Տոնայնություն',
      open: 'Բացել',
      sharedSetlist: 'Կիսվել է երգացանկով',
      send: 'Ուղարկել Չաթով',
      deleteTitle: 'Ջնջել զրույցը',
      deletePrompt: 'Ինչպե՞ս եք ցանկանում ջնջել այս զրույցը:',
      deleteMine: 'Ջնջել միայն ինձ համար',
      deleteEveryone: 'Ջնջել բոլորի համար',
      cancel: 'Չեղարկել'
    },
    call: {
      preparing: 'Միկրոֆոնը պատրաստվում է...',
      calling: 'Զանգահարում է...',
      ringing: 'Մուտքային աուդիոզանգ',
      connecting: 'Միանում է...',
      reconnecting: 'Կապը վերականգնվում է...',
      ended: 'Զանգն ավարտվեց',
      failed: 'Զանգի կապը խափանվեց',
      accept: 'Ընդունել',
      decline: 'Մերժել',
      end: 'Ավարտել',
      mute: 'Անջատել միկրոֆոնը',
      unmute: 'Միացնել միկրոֆոնը',
      speakerOn: 'Բարձրախոս (Միացված)',
      speakerOff: 'Առանց բարձրախոսի',
      speaker: 'Բարձրախոս',
      retry: 'Փորձել կրկին',
      close: 'Փակել',
      minimize: 'Փոքրացնել',
      expand: 'Բացել զանգը',
      resumeAudio: 'Միացնել ձայնը',
      audioOutput: 'Ձայնի ելք',
      defaultOutput: 'Ստանդարտ սարք',
      qualityGood: 'Կապը լավ է',
      qualityFair: 'Կապը միջին է',
      qualityPoor: 'Կապը թույլ է',
      errors: {
        microphone_denied: 'Միկրոֆոնի թույլտվությունը մերժված է։ Միացրեք այն սարքի կարգավորումներից։',
        microphone_unsupported: 'Այս սարքը չի աջակցում միկրոֆոնով զանգերին։',
        microphone_failed: 'Չհաջողվեց միացնել միկրոֆոնը։',
        microphone_lost: 'Միկրոֆոնի կապը կորել է։',
        offline: 'Ինտերնետ կապ չկա։ Սպասում ենք կապի վերականգնմանը։',
        connection_failed: 'Չհաջողվեց վերականգնել զանգը։',
        connection_unstable: 'Ինտերնետ կապը անկայուն է։',
        busy: 'Օգտատերը զբաղված է այլ զանգով։',
        rate_limited: 'Չափազանց շատ զանգի փորձեր։ Սպասեք մի փոքր։',
        invalid_target: 'Այս օգտատիրոջը զանգահարել հնարավոր չէ։',
        call_not_ringing: 'Այս զանգն այլևս հասանելի չէ։',
        call_start_failed: 'Չհաջողվեց սկսել զանգը։',
        default: 'Զանգի ժամանակ խնդիր առաջացավ։'
      }
    },
    contact: {
      intro: 'Ունե՞ք հարցեր, առաջարկներ կամ ցանկանում եք համագործակցել։ Մենք սիրով կպատասխանենք ձեզ:',
      docs: 'Փաստաթղթեր',
      office: 'Գրասենյակ',
      officeValue: 'Երևան, Հայաստան',
      phone: 'Հեռախոս',
      name: 'Անուն',
      email: 'Էլ. հասցե',
      message: 'Հաղորդագրություն',
      yourName: 'Ձեր անունը',
      yourQuestion: 'Գրեք ձեր հարցը...',
      submit: 'Ուղարկել',
      submitting: 'Ուղարկվում է...',
      success: 'Շնորհակալություն։ Ձեր հաղորդագրությունը ուղարկված է։',
      error: 'Սխալ տեղի ունեցավ: Խնդրում ենք փորձել կրկին:',
      networkError: 'Կապի խափանում: Խնդրում ենք ստուգել ինտերնետ կապը:'
    },
    newsState: {
      loading: 'Բեռնվում է...',
      notFound: 'Նորությունը չի գտնվել',
      back: 'Վերադառնալ',
      backToNews: '‹ Նորություններ'
    },
    hub: {
      searchPlaceholder: 'Որոնել երգեր, արտիստներ...',
      categories: {
        songs: 'Երգեր',
        artists: 'Արտիստներ',
        setlists: 'Երգացանկեր',
        teams: 'Ընկերներ',
        transposer: 'Ակորդների տրանսպոզ'
      },
      upcomingService: 'Առաջիկա Ծառայություն',
      startRehearsal: 'Սկսել Փորձը',
      myFavorites: 'Պահպանված երգեր',
      recentChords: 'Վերջին Ավելացվածները',
      latestNews: 'Համայնքի Նորություններ'
    },

    transposer: {
      kicker: 'Երաժշտական գործիք',
      title: 'Ակորդների տրանսպոզ',
      description: 'Գրեք կամ տեղադրեք ցանկացած ակորդային տեքստ և փոխեք տոնայնությունը՝ առանց կառուցվածքը կորցնելու։',
      clear: 'Մաքրել',
      controls: 'Տրանսպոզի կարգավորումներ',
      shift: 'Տեղափոխում',
      down: 'Իջեցնել մեկ կիսատոն',
      up: 'Բարձրացնել մեկ կիսատոն',
      resetShift: 'Վերադարձնել սկզբնական տոնայնությունը',
      semitones: 'կիսատոն',
      notation: 'Նոտագրություն',
      sharps: 'Դիեզ',
      flats: 'Բեմոլ',
      detectedKey: 'Առաջին ակորդը',
      inputLabel: 'Սկզբնական ակորդներ',
      inputHint: 'Տողերն ու բաժինները կպահպանվեն',
      placeholder: 'Verse\nC | Am | F | G\n\nChorus\nF | G | Em | Am',
      resultLabel: 'Տրանսպոզված արդյունք',
      originalKey: 'Սկզբնական տարբերակ',
      copy: 'Պատճենել',
      copied: 'Պատճենված է',
      copyError: 'Չհաջողվեց պատճենել արդյունքը։',
      empty: 'Մուտքագրեք ակորդներ՝ տրանսպոզված արդյունքը տեսնելու համար։'
    }
  },
  en: {
    auth: {
      loginTitle: 'Log in to your account',
      loginSubtitle: 'One unified login for your personal library, setlists, and notifications across web and app.',
      back: 'Go Back',
      welcomeBack: 'Welcome Back',
      welcomeBackDesc: 'Log in to sync your saved songs and setlists across all devices.',
      fillAllFields: 'Please fill out all fields',
      invalidLogin: 'Invalid email or password',
      invalidEmail: 'Enter a valid email address',
      invalidUsernameSpaces: 'Username cannot contain spaces',
      networkError: 'Network error, please try again.',
      saveLoginTitle: 'Save this login on this device?',
      saveLoginDesc: 'If you save it, you will stay signed in on this device until you log out yourself.',
      saveLoginConfirm: 'Save login',
      saveLoginSkip: 'Not now',
      saveLoginError: 'Could not save login',
      loginOrEmail: 'Email',
      password: 'Password',
      rememberMe: 'Remember me',
      forgotPassword: 'Forgot password?',
      pleaseWait: 'Please wait...',
      loginBtn: 'Log In',
      orContinue: 'or continue with',
      googleLogin: 'Log in with Google',
      googleReady: 'Ready to login',
      googleDisabled: 'Google sign-in is not configured yet. Please enable it in admin.',
      googleDisabledShort: 'Not configured yet',
      noAccount: 'Don\'t have an account?',
      createNow: 'Create now',
      guestEyebrow: 'Your music workspace',
      guestDescription: 'Open songs, change keys, and keep everything together in one secure account.',
      guestPreviewLabel: 'Chord preview',
      guestPreviewTitle: 'Ready for rehearsal',
      guestKey: 'Key:',
      guestOpenTransposer: 'Open transposer',
      guestLogin: 'Log in',
      guestBrowseSongs: 'Browse songs as guest',
      registerTitle: 'Create an account',
      registerSubtitle: 'Join worship teams from around the world. Save your songs and setlists on all devices.',
      joinCommunity: 'Join our community',
      joinDesc: 'Create a free account to manage your personal library and teams.',
      fullName: 'Full Name',
      username: 'Username',
      email: 'Email address',
      confirmPassword: 'Confirm Password',
      passwordMismatch: 'Passwords do not match',
      registerBtn: 'Register',
      hasAccount: 'Already have an account?',
      loginNow: 'Log In'
    },
    settings: {
      title: 'Settings',
      mobileMenu: 'Menu',
      tabs: {
        profile: 'Profile',
        app: 'App',
        security: 'Security',
        sessions: 'Sessions',
        requests: 'Requests',
        about: 'About the App',
        danger: 'Danger Zone'
      },
      app: {
        desc: 'Adjust app appearance and operating parameters.',
        themeMode: 'Appearance',
        themeModeDesc: 'Choose the app’s light or dark appearance.',
        darkTheme: 'Dark',
        lightTheme: 'Light',
        keepAwake: 'Keep Screen Awake',
        keepAwakeDesc: 'Screen will not turn off while reading song lyrics.',
        reduceMotion: 'Reduce Motion',
        reduceMotionDesc: 'Disables page transition effects for faster performance.',
        oledMode: 'OLED Dark Mode (True Black)',
        oledModeDesc: 'Uses absolute black background (saves battery on OLED screens).',
        oledDarkOnly: 'Available only in dark mode.',
        outlinedChords: 'Outlined Chords',
        outlinedChordsDesc: 'Chords are displayed as individual buttons for easier reading.',
        chordColor: 'Chord Color',
        chordStyle: 'Chord style',
        standardChords: 'Standard',
        colorGold: 'Gold',
        colorBlue: 'Blue',
        colorGreen: 'Green',
        colorRed: 'Red',
        colorWhite: 'White',
        colorBlack: 'Black',
        enabled: 'Enabled',
        disabled: 'Disabled',
        enable: 'Enable',
        disable: 'Disable',
        saved: 'Saved'
      },
      about: {
        tagline: 'Songs, chords, and team collaboration in one app.',
        version: 'App version',
        status: 'App status',
        statusActive: 'Active (Operational)',
        statusMaintenance: 'Maintenance',
        statusScheduled: 'Scheduled maintenance',
        platform: 'Installation type',
        offline: 'Offline access',
        available: 'Available',
        releaseType: 'Release type',
        releaseTypes: {
          major: 'Major release',
          feature: 'Feature update',
          patch: 'Patch update',
          hotfix: 'Hotfix',
          maintenance: 'Maintenance update',
          content: 'Content update'
        },
        updated: 'Last updated',
        licenseTitle: 'Licenses',
        licenseText: 'Worship Platform is proprietary software of PM Studio. Open-source libraries are distributed under their respective licenses.',
        privacy: 'Privacy',
        terms: 'Terms',
        support: 'Support',
        rights: 'All rights reserved.'
      },
      profile: {
        title: 'Personal Information',
        desc: 'Edit your basic details.',
        name: 'Full Name',
        birthDate: 'Birth Date',
        gender: 'Gender',
        genderMale: 'Male',
        genderFemale: 'Female',
        genderOther: 'Other',
        phone: 'Phone Number',
        save: 'Save Changes',
        success: 'Profile updated successfully'
      },
      security: {
        title: 'Security & Login',
        desc: 'Manage your password and email address.',
        emailStatus: 'Email Status',
        unverified: 'Unverified',
        verified: 'Verified',
        sendVerify: 'Send verification email',
        changeEmail: 'Change Email',
        newEmail: 'New Email Address',
        saveEmail: 'Save Email',
        changePassword: 'Change Password',
        oldPassword: 'Current Password',
        newPassword: 'New Password',
        savePassword: 'Update Password',
        forgotPassword: 'Forgot Password?',
        emailSent: 'Verification link sent',
        passChanged: 'Password changed successfully'
      },
      sessions: {
        title: 'Active Sessions',
        desc: 'Here you can see the devices where you are currently logged in.',
        closeOther: 'Close Others',
        currentDevice: 'Current Device',
        remembered: 'Remembered',
        rememberTitle: 'Remember me on this device',
        rememberEnabled: 'Enabled',
        rememberDisabled: 'Disabled',
        rememberDescOn: 'Your login is saved on this device and will stay active until you log out.',
        rememberDescOff: 'If you enable it, this device will stay signed in until you log out.',
        rememberEnableBtn: 'Enable',
        rememberDisableBtn: 'Disable',
        rememberUpdatedOn: 'Remember me enabled',
        rememberUpdatedOff: 'Remember me disabled',
        logout: 'Log Out',
        empty: 'No sessions found.'
      },
      requests: {
        title: 'My Requests',
        desc: 'Status of your new song or edit requests.',
        type: 'Type',
        date: 'Date',
        adminNote: 'Admin Response',
        empty: 'You have no sent requests yet.'
      },
      danger: {
        title: 'Danger Zone',
        desc: 'Account deletion is irreversible. All saved songs and data will be lost.',
        deleteBtn: 'Delete Account',
        modalTitle: 'Confirm Deletion',
        modalDesc: 'Please enter your password to permanently delete your account.',
        password: 'Password',
        cancel: 'Cancel',
        confirm: 'Confirm & Delete'
      }
    },
    dashboard: {
      library: 'Song Library',
      search: 'Search song...',
      loginSetlists: 'Access your setlists...',
      manageSetlists: 'Manage Setlists',
      loginPrompt: 'Log in to create setlists',
      loginBtn: 'Log In',
      emptySetlist: 'There are no songs in this setlist yet.',
      key: 'Key:',
      openStageReader: 'Open Stage Reader',
      emptyTitle: 'With all my heart and soul I will sing to You',
      emptyVerse: 'Verse/Chorus',
      emptyBridge: 'Bridge'
    },
    nav: {
      home: 'Home',
      songs: 'Songs',
      transposer: 'Transpose',
      sets: 'Sets',
      friends: 'Friends',
      community: 'Community',
      pricing: 'Pricing',
      resources: 'Resources',
      news: 'News',
      login: 'Log In',
      register: 'Get Started',
      logout: 'Log Out',
      refresh: 'Refresh',
      refreshing: 'Refreshing…',
      retry: 'Try again',
      retryOnline: 'Internet is still unavailable. Connect and try again.',
      online: 'Online',
      offline: 'Offline',
      search: 'Search songs…',
      setlists: 'Setlists'
    },
    megaMenu: {
      features: 'Features',
      music: 'Music',
      management: 'Management',
      latestArrival: 'Latest Updates',
      discoverSongs: 'Discover new songs, chords, and build your setlists.',
      readArticle: 'Read more »',
      communityDesc: 'Join our community, share your experience and connect with others.',
      joinNow: 'Join now »',
      materials: 'Materials',
      info: 'Information',
      contacts: 'Contacts'
    },
    landing: {
      heroTitle1: 'Equip Your',
      heroTitle2: 'Worship Team',
      heroSubtitle: 'Streamline Service Planning, Access Modern Chords, and Collaborate Freely.',
      startBtn: 'Start for Free',
      watchDemo: 'Watch Demo',
      popularSongs: 'Popular Songs',
      communityPicks: 'Community Picks',
      browse: 'Browse',
      browseSongs: 'Songs',
      browseArtists: 'Artists',
      browseCollections: 'Collections',
      browseByKey: 'By Key',
      browseByBPM: 'By BPM',
      heroSubtitle1: 'Smarter',
      latestNews: 'Latest News',
      footerRights: '© 2026 Worship Platform. All rights reserved.',
      unknownArtist: 'Unknown Artist',
      picks: [
        { title: 'Gratitude', artist: 'Brandon Lake', meta: 'Sets 14 · Rev 1 · 9380 plays' },
        { title: 'Graves Into Gardens', artist: 'Bethel Worship', meta: 'Sets 17 · Rev 5 · 320 plays' },
        { title: 'Way Maker', artist: 'Sinach', meta: 'Sets 22 · Rev 2 · 15k plays' }
      ],
      newsItems: [
        { date: 'Apr 12, 2024', title: 'New Feature: Dynamic Transposition!', desc: 'Worship teams can now instantly transpose songs to any key with a single click.' },
        { date: 'Apr 28, 2024', title: 'Mastering Your Setlist Planning', desc: 'Discover how our setlist builder helps worship leaders plan more effectively.' },
        { date: 'May 18, 2024', title: 'Collaborate with Your Whole Team', desc: 'Share chords, notes, and rehearsal plans with every member of your worship team.' }
      ],
      footer: {
        product: 'Product',
        company: 'Company',
        resources: 'Resources',
        legal: 'Legal',
        songs: 'Songs',
        teams: 'Teams',
        pricing: 'Pricing',
        setlists: 'Setlists',
        about: 'About',
        blog: 'Blog',
        careers: 'Careers',
        community: 'Community',
        documentation: 'Documentation',
        tutorials: 'Tutorials',
        support: 'Support',
        privacyPolicy: 'Privacy Policy',
        terms: 'Terms',
        cookies: 'Cookies'
      }
    },
    songs: {
      title: 'Song Library',
      search: 'Search songs, artists...',
      tableTitle: 'Title',
      tableKey: 'Key',
      tableBpm: 'BPM',
      tableAuthor: 'Artist',
      tableAdded: 'Added',
      openReader: 'Open',
      noResults: 'No results found',
      loading: 'Loading...',
      loadMore: 'Load More',
      backToTop: 'Back to top',
      sortTitle: 'Sort: Title A–Z',
      sortBpm: 'Sort: BPM',
      sortKey: 'Sort: Key',
      sortRecent: 'Recently Added',
      unknownArtist: 'Unknown Artist',
      removeFromFav: 'Remove',
      addToFav: 'Save',
    },
    songView: {
      added: 'Song saved ♥',
      removed: 'Removed from saved songs',
      loading: 'Loading...',
      error: 'Failed to fetch song',
      back: 'Go Back',
      useFlats: 'b',
      transpose: 'Transpose',
      capoSub: 'Capo',
      fontSize: 'Font',
      downloadTxt: 'Download TXT',
      requestEdit: 'Edit',
      chordsOnly: 'Chords',
      lyricsOnly: 'Lyrics',
      bothModes: 'Both',
      noCapo: 'No Capo',
      clear: 'Clear',
      keyPrefix: 'Key:',
      playAs: 'Play as:',
      keySavedAlert: 'Key saved',
      keyIsSaved: '✓ Saved',
      saveKey: 'Save new key',
      semitones: 'semitones',
      reset: 'Reset',
      flats: '♭ Flats',
      sharps: '♯ Sharps',
      signs: 'Signs',
      noLyrics: 'Lyrics are not available',
      linkCopied: 'Link copied',
      linkCopyError: 'Failed to copy link',
      setlistTitle: 'Setlist',
      key: 'Key:',
      tempo: 'Tempo:',
      addToSetlist: 'Add to Setlist',
      download: 'Download',
      edit: 'Edit',
      copied: 'Copied',
      copyError: 'Error copying',
      copyContent: 'Copy Song',
      copyLink: 'Copy Link'
    },
    songRequest: {
      title: 'Song Request',
      titleNew: 'Suggest New Song',
      titleEdit: 'Edit Song',
      badgeNew: '✨ New Song Suggestion',
      badgeEdit: '✏️ Edit Suggestion',
      modeQuick: '⚡ Quick Request',
      modeFull: '🎼 Full Details',
      quickHint: 'Enter the song title, artist, or YouTube / MP3 link. Our team will find the song, arrange the chords, and add it!',
      quickTitlePlaceholder: 'Example: Bless the Lord or Hillsong - Oceans',
      quickNotesPlaceholder: 'Paste YouTube / MP3 link or notes (e.g., "Please add in key of G")...',
      needLogin: 'Please log in to submit a request.',
      songDataLoadError: 'Failed to load song data.',
      titleHy: 'Title (Armenian)',
      titleLat: 'Title (Latin)',
      titleEn: 'Title (English)',
      titleRu: 'Title (Russian)',
      artist: 'Artist / Band',
      songKey: 'Key',
      selectKeyPlaceholder: '-- Select Key --',
      bpm: 'BPM (Tempo)',
      tags: 'Tags',
      chords: 'Chords (standard format)',
      lyrics: 'Lyrics (without chords)',
      lyricsAndChordsSection: 'Chords & Lyrics',
      chordsPreview: 'Chords Preview',
      preview: '👁️ Preview',
      edit: '✏️ Edit',
      message: 'Message to moderator (optional)',
      notesPlaceholder: 'Write additional notes or comments for moderators...',
      basicsSection: 'Basic Information',
      musicSection: 'Music Details',
      submit: 'Submit Request',
      submitBtnNew: 'Submit Song',
      submitBtnEdit: 'Save & Submit Edit',
      submitting: 'Submitting...',
      success: 'Request submitted successfully!',
      submitError: 'Failed to submit request',
      networkError: 'Network error',
      backToSong: 'Back to Song'
    },
    setlists: {
      heroTitle: 'Worship Setlists',
      heroSubtitle: 'Manage your setlists, plan services, and collaborate with your team.',
      statTotalSets: 'Setlists',
      statTotalSongs: 'Total Songs',
      statTeamSets: 'Team Sets',
      tabAll: 'All',
      tabPersonal: 'Personal',
      tabTeam: 'Team',
      tabShared: 'Shared',
      sortNewest: 'Newest first',
      sortOldest: 'Oldest first',
      sortName: 'By name',
      sortItems: 'By song count',
      noDate: 'No date',
      backToSetlists: 'Setlists',
      publicBadge: 'Public Setlist',
      liveMode: 'Live Mode',
      saveToAccount: 'Save to My Setlists',
      copyLink: 'Copy Link',
      copied: 'Copied!',
      saving: 'Saving...',
      statItems: 'Items',
      statSongs: 'Songs',
      statSections: 'Sections',
      statRequired: 'Required',
      itemsTitle: 'Setlist Songs',
      keyLabel: 'Key',
      required: 'Required',
      section: 'Section',
      errorTitle: 'Setlist Unavailable',
      invalidToken: 'Invalid or missing share link.',
      allSetlists: 'View Setlists',
      importedTag: 'Copy',
      loginPrompt: 'Please log in to create and manage setlists.',
      newSetlist: 'New Setlist',
      errorLoad: 'Failed to load setlists',
      colTitle: 'Title',
      colDate: 'Date',
      colSongs: 'Songs',
      colType: 'Type',
      loading: 'Loading...',
      empty: 'You have no saved setlists',
      unknownDate: 'Unknown',
      songsCount: 'songs',
      typeShared: 'Shared',
      typePersonal: 'Personal',
      edit: 'Edit',
      errorFetch: 'Failed to fetch setlist data',
      goBack: 'Go Back',
      addSong: 'Add Song',
      closeSearch: 'Close Search',
      searchPlaceholder: 'Search song to add...',
      searchBtn: 'Search',
      addBtn: 'Add',
      emptySetlist: 'Setlist is empty. Add songs using search.',
      noKey: 'None',
      remove: 'Remove',
      confirmRemove: 'Are you sure you want to remove this?',
      errorOccurred: 'An error occurred',
      searchResults: 'Search Results',
      editSetlist: 'Edit Setlist',
      nameField: 'Name',
      dateField: 'Date / Day',
      descField: 'Description',
      cancelBtn: 'Cancel',
      saveBtn: 'Save',
      savingBtn: 'Saving...',
      namePlaceholder: 'e.g. Sunday Service',
      assignTeam: 'Assign to Team (Optional)',
      personalTeam: '-- Personal --',
      createBtn: 'Create',
      creatingBtn: 'Creating...',
      deleteBtn: 'Delete Setlist',
      confirmDelete: 'Are you sure you want to delete this setlist? This action cannot be undone.',
      limitReached: 'Setlist limit reached.',
      createFailed: 'Failed to create setlist.',
      networkError: 'Network error'
    },
    news: { title: 'News & Updates' },
    teams: {
      hero: 'Lead Your Team With Confidence',
      badge: 'For Worship Leaders',
      subtitle: 'Everything you need to coordinate your worship team in one powerful, easy-to-use platform.',
      cta: 'See Plans & Pricing',
      ctaJoin: 'Start Free Trial',
      dashboard: 'Go to Dashboard',
      featuresTitle: 'Everything Your Team Needs',
      ctaTitle: 'Ready to Equip Your Team?',
      ctaSub: 'Join thousands of worship teams already using the Worship Platform.',
      newTeamNamePrompt: 'New Team Name:',
      memberEmailPrompt: 'Member Email:',
      addedAlert: 'Added',
      createNewTeamBtn: 'Create New Team',
      upgradeRequired: 'Upgrade Required',
      cancelBtn: 'Cancel',
      seePlansBtn: 'See Plans',
      noTeams: 'You have no teams yet.',
      membersCountLabel: 'members',
      roles: ['Guitarist', 'Pianist', 'Drummer', 'Vocalist', 'Brass'],
      featuresList: [
        { icon: '👥', title: 'Team Members', desc: 'Add musicians, vocalists, and tech team members. Assign roles and manage permissions.' },
        { icon: '📋', title: 'Shared Setlists', desc: 'Build and share setlists with your entire team. Everyone sees the same plan in real time.' },
        { icon: '🎵', title: 'Chord Sheets', desc: 'Give every team member access to chord charts, lyrics, and arrangement notes.' },
        { icon: '🔔', title: 'Rehearsal Alerts', desc: 'Send automatic reminders and schedule rehearsals so no one misses a practice.' },
        { icon: '📊', title: 'Analytics', desc: 'See which songs are used most, track team activity, and measure engagement.' },
        { icon: '💬', title: 'Team Chat', desc: 'Communicate directly inside the platform. No need for separate messaging apps.' }
      ],
      addMemberPrompt: 'Enter new member email:',
      confirmRemoveMember: 'Are you sure you want to remove this member?',
      confirmDeleteTeam: 'Are you sure you want to delete this team entirely?',
      teamDetails: 'Team Details',
      deleteTeamBtn: 'Delete Team',
      addMemberBtn: '+ Add Member',
      teamMembersListTitle: 'Team Members',
      noMembers: 'No members in this team yet.'
    },
    favorites: {
      errorLoad: 'Failed to load saved songs',
      loginTitle: 'Log in',
      loginPrompt: 'Please log in to see your saved songs.',
      loginBtn: 'Log in',
      title: 'Saved Songs',
      savedSongs: 'saved songs',
      loading: 'Loading...',
      favoriteTag: 'Saved',
      playlist: 'Playlist',
      confirmRemove: 'Remove this song from saved songs?',
      keyTag: 'Key:',
      openSong: 'Open Song',
      noFavorites: 'You have no saved songs yet.',
      emptyDesc: 'Saved songs will appear here so you can jump back to them quickly.',
      openFirst: 'Open first song',
      browseSongs: 'Browse songs',
      viewAll: 'View all',
      retry: 'Try again',
      filterAll: 'All',
      filterAndSort: 'Filter and sort',
      keyFilter: 'Key',
      resetFilters: 'Reset',
      applyFilters: 'Apply',
      sortLabel: 'Sort by',
      sortSavedNewest: 'Recently saved',
      sortSavedOldest: 'First saved',
      sortTitle: 'Title A-Z',
      sortArtist: 'Artist A-Z',
      sortKey: 'Key',
      sortBpmAsc: 'BPM low to high',
      sortBpmDesc: 'BPM high to low',
      noFilterResults: 'No songs found for this filter',
      noFilterResultsDesc: 'Try another key or return to all saved songs.',
      filterReset: 'Show all'
    },
    notifications: {
      title: 'Notifications',
      markAllRead: 'Mark all as read',
      loading: 'Loading...',
      newNotification: 'New notification',
      emptyTitle: 'No new notifications',
      emptyDesc: 'Notifications about your team, setlists, and other important events will appear here.'
    },
    pricing: {
      badge: 'Simple Pricing',
      title: 'Plans for Every Team',
      subtitle: 'Start free. Upgrade as your ministry grows. Cancel anytime.',
      faqTitle: 'Frequently Asked Questions',
      popular: 'Most Popular'
    },
    community: {
      title: 'Community Forum',
      subtitle: 'Connect with worship leaders and musicians from around the world.',
      trending: '🔥 Trending Topics',
      resources: '📌 Resources',
      browseLibrary: '🎵 Browse Song Library',
      createSetlist: '📋 Create a Setlist',
      latestNews: '📰 Latest News',
      replies: 'replies',
      share: 'Share'
    },
    resources: {
      title: 'Resources',
      subtitle: 'Guides, tutorials, and tools to help your worship team thrive.',
      search: 'Search resources…'
    },

    profile: {
      title: 'Profile',
      desc: 'Manage your account and preferences.',
      currentPlan: 'Current Plan',
      loading: 'Loading...',
      upgradePlan: 'Upgrade Plan',
      savedSongs: 'Saved Songs',
      myTeams: 'My Teams',
      accountSettings: 'Account Settings',
      language: 'Language',
      logout: 'Logout',
      selectLanguage: 'Select Language',
      pushOn: 'Enabled. You will receive new chat messages on time.',
      pushOff: 'Turn this on so you do not miss new chat messages.',
      pushNote: 'If notifications are disabled, you will not receive new chat messages. This is required for the app.',
      pushMissingManager: 'An error occurred while enabling notifications.',
      pushDisableConfirm: 'If you disable notifications, you will not receive new chat messages. Are you sure?',
      pushNotSupported: 'Your device or browser does not support push notifications. Make sure the app is added to your home screen.',
      pushEnableError: 'Notifications were denied or an error occurred.'
    },
    friends: {
      confirmRemove: 'Are you sure?',
      tabs: {
        chats: 'Chats',
        myFriends: 'My Friends',
        add: 'Add',
        requests: 'Requests'
      },
      emptyFriends: 'You do not have friends yet. Go to the Add tab to find new friends.',
      chat: 'Chat',
      remove: 'Remove',
      findTitle: 'Find friends',
      findDesc: 'Search users by name or email',
      searchPlaceholder: 'Enter a name or email...',
      alreadyFriends: 'Already friends (Chat)',
      cancelRequest: 'Cancel request',
      acceptRequest: 'Accept request',
      addFriend: '+ Add',
      searchEmpty: 'Nothing found for “{{query}}”.',
      incomingTitle: 'Incoming requests',
      outgoingTitle: 'Sent requests',
      noIncoming: 'You have no new requests.',
      noOutgoing: 'You do not have pending sent requests.',
      accept: 'Accept',
      reject: 'Reject',
      cancel: 'Cancel'
    },
    chat: {
      today: 'Today',
      yesterday: 'Yesterday',
      monthsGenitive: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
      deletedOrUnavailable: 'This conversation was deleted or is unavailable.',
      group: 'Group',
      offline: 'Offline',
      online: 'Online',
      lastSeen: 'Last seen:',
      friendFallback: 'Friend',
      chatFallback: 'Chat',
      deleteTooltip: 'Delete conversation',
      loadingOlder: 'Loading older messages...',
      emptyTitle: 'Start the conversation',
      emptySubtitle: 'Start typing here...',
      placeholder: 'Type a message...',
      sent: 'Sent',
      seen: 'Seen',
      key: 'Key',
      open: 'Open',
      sharedSetlist: 'Shared a Setlist',
      send: 'Send in Chat',
      deleteTitle: 'Delete conversation',
      deletePrompt: 'How would you like to delete this conversation?',
      deleteMine: 'Delete only for me',
      deleteEveryone: 'Delete for everyone',
      cancel: 'Cancel'
    },
    call: {
      preparing: 'Preparing microphone...',
      calling: 'Calling...',
      ringing: 'Incoming audio call',
      connecting: 'Connecting...',
      reconnecting: 'Restoring connection...',
      ended: 'Call ended',
      failed: 'Call connection failed',
      accept: 'Accept',
      decline: 'Decline',
      end: 'End call',
      mute: 'Mute microphone',
      unmute: 'Unmute microphone',
      speakerOn: 'Speaker On',
      speakerOff: 'Speaker Off',
      speaker: 'Speaker',
      retry: 'Try again',
      close: 'Close',
      minimize: 'Minimize',
      expand: 'Open call',
      resumeAudio: 'Enable audio',
      audioOutput: 'Audio output',
      defaultOutput: 'Default device',
      qualityGood: 'Good connection',
      qualityFair: 'Fair connection',
      qualityPoor: 'Weak connection',
      errors: {
        microphone_denied: 'Microphone permission was denied. Enable it in your device settings.',
        microphone_unsupported: 'This device does not support microphone calls.',
        microphone_failed: 'The microphone could not be started.',
        microphone_lost: 'The microphone connection was lost.',
        offline: 'There is no internet connection. Waiting to reconnect.',
        connection_failed: 'The call could not be restored.',
        connection_unstable: 'Your internet connection is unstable.',
        busy: 'The user is busy on another call.',
        rate_limited: 'Too many call attempts. Please wait a moment.',
        invalid_target: 'This user cannot be called.',
        call_not_ringing: 'This call is no longer available.',
        call_start_failed: 'The call could not be started.',
        default: 'A call error occurred.'
      }
    },
    contact: {
      intro: 'Have questions, ideas, or want to collaborate? We would love to hear from you.',
      docs: 'Documentation',
      office: 'Office',
      officeValue: 'Yerevan, Armenia',
      phone: 'Phone',
      name: 'Name',
      email: 'Email',
      message: 'Message',
      yourName: 'Your name',
      yourQuestion: 'Write your question...',
      submit: 'Send',
      submitting: 'Sending...',
      success: 'Thank you. Your message has been sent.',
      error: 'Something went wrong. Please try again.',
      networkError: 'Connection problem. Please check your internet connection.'
    },
    newsState: {
      loading: 'Loading...',
      notFound: 'News article not found',
      back: 'Go back',
      backToNews: '‹ News'
    },
    hub: {
      searchPlaceholder: 'Search songs, artists...',
      categories: {
        songs: 'Songs',
        artists: 'Artists',
        setlists: 'Setlists',
        teams: 'Friends',
        transposer: 'Chord transposer'
      },
      upcomingService: 'Upcoming Service',
      startRehearsal: 'Start Rehearsal',
      myFavorites: 'Saved Songs',
      recentChords: 'Recently Added',
      latestNews: 'Community News'
    },

    transposer: {
      kicker: 'Music tool',
      title: 'Chord Transposer',
      description: 'Type or paste any chord text and change its key without losing the original structure.',
      clear: 'Clear',
      controls: 'Transpose controls',
      shift: 'Shift',
      down: 'Move down one semitone',
      up: 'Move up one semitone',
      resetShift: 'Reset to the original key',
      semitones: 'semitones',
      notation: 'Notation',
      sharps: 'Sharps',
      flats: 'Flats',
      detectedKey: 'First chord',
      inputLabel: 'Original chords',
      inputHint: 'Lines and sections are preserved',
      placeholder: 'Verse\nC | Am | F | G\n\nChorus\nF | G | Em | Am',
      resultLabel: 'Transposed result',
      originalKey: 'Original version',
      copy: 'Copy',
      copied: 'Copied',
      copyError: 'Could not copy the result.',
      empty: 'Enter chords to see the transposed result.'
    },

  },
  ru: {
    auth: {
      loginTitle: 'Войдите в свой аккаунт',
      loginSubtitle: 'Единый вход для вашей личной библиотеки, сет-листов и уведомлений на сайте и в приложении.',
      back: 'Назад',
      welcomeBack: 'С возвращением',
      welcomeBackDesc: 'Войдите, чтобы синхронизировать сохраненные песни и сет-листы на всех устройствах.',
      fillAllFields: 'Пожалуйста, заполните все поля',
      invalidLogin: 'Неверный email или пароль',
      invalidEmail: 'Введите корректный email адрес',
      invalidUsernameSpaces: 'Логин не может содержать пробелы',
      networkError: 'Ошибка сети, попробуйте еще раз.',
      saveLoginTitle: 'Сохранить вход на этом устройстве?',
      saveLoginDesc: 'Если сохранить вход, на этом устройстве не нужно будет входить снова, пока вы сами не выйдете из аккаунта.',
      saveLoginConfirm: 'Сохранить вход',
      saveLoginSkip: 'Не сейчас',
      saveLoginError: 'Не удалось сохранить вход',
      loginOrEmail: 'Email',
      password: 'Пароль',
      rememberMe: 'Запомнить меня',
      forgotPassword: 'Забыли пароль?',
      pleaseWait: 'Пожалуйста, подождите...',
      loginBtn: 'Войти',
      orContinue: 'или продолжите',
      googleLogin: 'Войти через Google',
      googleReady: 'Готово к входу',
      googleDisabled: 'Вход через Google еще не настроен. Включите его в админке.',
      googleDisabledShort: 'Еще не настроено',
      noAccount: 'Нет аккаунта?',
      createNow: 'Создать сейчас',
      guestEyebrow: 'Ваше музыкальное пространство',
      guestDescription: 'Открывайте песни, меняйте тональность и храните всё в одном защищённом аккаунте.',
      guestPreviewLabel: 'Предпросмотр аккордов',
      guestPreviewTitle: 'Готово к репетиции',
      guestKey: 'Тон:',
      guestOpenTransposer: 'Открыть транспозер',
      guestLogin: 'Войти',
      guestBrowseSongs: 'Открыть песни как гость',
      registerTitle: 'Создать аккаунт',
      registerSubtitle: 'Присоединяйтесь к командам прославления со всего мира. Сохраняйте песни на всех устройствах.',
      joinCommunity: 'Присоединяйтесь к сообществу',
      joinDesc: 'Создайте бесплатный аккаунт для управления библиотекой и командами.',
      fullName: 'Имя Фамилия',
      username: 'Логин',
      email: 'Email адрес',
      confirmPassword: 'Подтвердите Пароль',
      passwordMismatch: 'Пароли не совпадают',
      registerBtn: 'Зарегистрироваться',
      hasAccount: 'Уже есть аккаунт?',
      loginNow: 'Войти'
    },
    settings: {
      title: 'Настройки',
      mobileMenu: 'Меню',
      tabs: {
        profile: 'Профиль',
        app: 'Приложение',
        security: 'Безопасность',
        sessions: 'Сессии',
        requests: 'Запросы',
        about: 'О приложении',
        danger: 'Опасная зона'
      },
      app: {
        desc: 'Настройте внешний вид и параметры работы приложения.',
        themeMode: 'Оформление',
        themeModeDesc: 'Выберите светлое или темное оформление приложения.',
        darkTheme: 'Темная',
        lightTheme: 'Светлая',
        keepAwake: 'Не выключать экран',
        keepAwakeDesc: 'Экран не погаснет при чтении текстов песен.',
        reduceMotion: 'Уменьшение движения',
        reduceMotionDesc: 'Отключает эффекты перехода страниц для более быстрой работы.',
        oledMode: 'Режим OLED (Истинный черный)',
        oledModeDesc: 'Использует абсолютно черный фон (экономит заряд на OLED экранах).',
        oledDarkOnly: 'Доступно только в темном режиме.',
        outlinedChords: 'Обведенные аккорды',
        outlinedChordsDesc: 'Аккорды отображаются в виде отдельных кнопок для удобства чтения.',
        chordColor: 'Цвет аккордов',
        chordStyle: 'Стиль аккордов',
        standardChords: 'Стандартный',
        colorGold: 'Золотой',
        colorBlue: 'Синий',
        colorGreen: 'Зеленый',
        colorRed: 'Красный',
        colorWhite: 'Белый',
        colorBlack: 'Черный',
        enabled: 'Включено',
        disabled: 'Отключено',
        enable: 'Включить',
        disable: 'Отключить',
        saved: 'Сохранено'
      },
      about: {
        tagline: 'Песни, аккорды и командная работа в одном приложении.',
        version: 'Версия приложения',
        status: 'Статус приложения',
        statusActive: 'Активный (Работает)',
        statusMaintenance: 'Техническое обслуживание',
        statusScheduled: 'Запланированное обслуживание',
        platform: 'Тип установки',
        offline: 'Работа офлайн',
        available: 'Доступна',
        releaseType: 'Тип выпуска',
        releaseTypes: {
          major: 'Крупное обновление',
          feature: 'Новая функция',
          patch: 'Исправление',
          hotfix: 'Срочное исправление',
          maintenance: 'Техническое обновление',
          content: 'Обновление контента'
        },
        updated: 'Последнее обновление',
        licenseTitle: 'Лицензии',
        licenseText: 'Worship Platform является проприетарным программным обеспечением PM Studio. Библиотеки с открытым исходным кодом распространяются по соответствующим лицензиям.',
        privacy: 'Конфиденциальность',
        terms: 'Условия',
        support: 'Поддержка',
        rights: 'Все права защищены.'
      },
      profile: {
        title: 'Личные данные',
        desc: 'Редактируйте свою основную информацию.',
        name: 'Имя Фамилия',
        birthDate: 'Дата рождения',
        gender: 'Пол',
        genderMale: 'Мужской',
        genderFemale: 'Женский',
        genderOther: 'Другое',
        phone: 'Телефон',
        save: 'Сохранить',
        success: 'Данные успешно обновлены'
      },
      security: {
        title: 'Безопасность и Вход',
        desc: 'Управление паролем и email адресом.',
        emailStatus: 'Статус Email',
        unverified: 'Не подтвержден',
        verified: 'Подтвержден',
        sendVerify: 'Отправить письмо',
        changeEmail: 'Изменить Email',
        newEmail: 'Новый Email',
        saveEmail: 'Сохранить Email',
        changePassword: 'Изменить пароль',
        oldPassword: 'Текущий пароль',
        newPassword: 'Новый пароль',
        savePassword: 'Обновить пароль',
        forgotPassword: 'Забыли пароль?',
        emailSent: 'Письмо отправлено',
        passChanged: 'Пароль успешно изменен'
      },
      sessions: {
        title: 'Активные сессии',
        desc: 'Здесь показаны устройства, на которых выполнен вход.',
        closeOther: 'Закрыть другие',
        currentDevice: 'Текущее устройство',
        remembered: 'Запомнено',
        rememberTitle: 'Запомнить меня на этом устройстве',
        rememberEnabled: 'Включено',
        rememberDisabled: 'Выключено',
        rememberDescOn: 'Вход сохранен на этом устройстве и останется активным, пока вы сами не выйдете.',
        rememberDescOff: 'Если включить, вход на этом устройстве сохранится до выхода из аккаунта.',
        rememberEnableBtn: 'Включить',
        rememberDisableBtn: 'Выключить',
        rememberUpdatedOn: 'Запомнить меня включено',
        rememberUpdatedOff: 'Запомнить меня выключено',
        logout: 'Выйти',
        empty: 'Сессий не найдено.'
      },
      requests: {
        title: 'Мои запросы',
        desc: 'Статус ваших запросов на добавление или изменение песен.',
        type: 'Тип',
        date: 'Дата',
        adminNote: 'Ответ админа',
        empty: 'У вас пока нет запросов.'
      },
      danger: {
        title: 'Опасная зона',
        desc: 'Удаление аккаунта необратимо. Все данные будут потеряны.',
        deleteBtn: 'Удалить аккаунт',
        modalTitle: 'Подтвердите удаление',
        modalDesc: 'Пожалуйста, введите пароль для удаления аккаунта.',
        password: 'Пароль',
        cancel: 'Отмена',
        confirm: 'Подтвердить и Удалить'
      }
    },
    dashboard: {
      library: 'Библиотека Песен',
      search: 'Поиск песни...',
      loginSetlists: 'Доступ к сет-листам...',
      manageSetlists: 'Управление сет-листами',
      loginPrompt: 'Войдите, чтобы создавать сет-листы',
      loginBtn: 'Войти',
      emptySetlist: 'В этом сет-листе пока нет песен.',
      key: 'Том:',
      openStageReader: 'Открыть Stage Reader',
      emptyTitle: 'Всем сердцем и душой буду петь Тебе',
      emptyVerse: 'Куплет/Припев',
      emptyBridge: 'Бридж'
    },
    nav: {
      home: 'Главная',
      songs: 'Песни',
      transposer: 'Транспонирование',
      sets: 'Сет-листы',
      teams: 'Команда',
      community: 'Сообщество',
      pricing: 'Цены',
      resources: 'Ресурсы',
      news: 'Новости',
      login: 'Войти',
      register: 'Начать',
      logout: 'Выйти',
      refresh: 'Обновить',
      refreshing: 'Обновление…',
      retry: 'Повторить',
      retryOnline: 'Интернет по-прежнему недоступен. Подключитесь и повторите попытку.',
      online: 'Онлайн',
      offline: 'Офлайн',
      search: 'Искать песни…',
      setlists: 'Сет-листы'
    },
    megaMenu: {
      features: 'Возможности',
      music: 'Музыка',
      management: 'Управление',
      latestArrival: 'Обновления',
      discoverSongs: 'Откройте для себя новые песни, аккорды и создавайте сет-листы.',
      readArticle: 'Читать далее »',
      communityDesc: 'Присоединяйтесь к нашему сообществу и делитесь опытом.',
      joinNow: 'Присоединиться »',
      materials: 'Материалы',
      info: 'Информация',
      contacts: 'Контакты'
    },
    landing: {
      heroTitle1: 'Снарядите',
      heroTitle2: 'Вашу Команду',
      heroSubtitle: 'Планирование служений, доступ к аккордам и командное сотрудничество — на одной платформе.',
      startBtn: 'Начать бесплатно',
      watchDemo: 'Смотреть Demo',
      popularSongs: 'Популярные Песни',
      communityPicks: 'Выбор сообщества',
      browse: 'Просмотр',
      browseSongs: 'Песни',
      browseArtists: 'Артисты',
      browseCollections: 'Коллекции',
      browseByKey: 'По тональности',
      browseByBPM: 'По темпу',
      heroSubtitle1: 'Умнее',
      latestNews: 'Последние Новости',
      footerRights: '© 2026 Worship Platform. Все права защищены.',
      unknownArtist: 'Неизвестный исполнитель',
      picks: [
        { title: 'Gratitude', artist: 'Brandon Lake', meta: 'Сет-листы 14 · 9380 просмптров' },
        { title: 'Graves Into Gardens', artist: 'Bethel Worship', meta: 'Сет-листы 17 · 320 просмотров' },
        { title: 'Way Maker', artist: 'Sinach', meta: 'Сет-листы 22 · 15k просмотров' }
      ],
      newsItems: [
        { date: 'Апр 12, 2024', title: 'Новая функция: Динамическая Тональность!', desc: 'Теперь команды могут транспонировать песни в один клик.' },
        { date: 'Апр 28, 2024', title: 'Мастер планирования', desc: 'Узнайте, как наш инструмент помогает планировать служение.' },
        { date: 'Май 18, 2024', title: 'Работайте вместе', desc: 'Делитесь аккордами и планами со всей командой.' }
      ],
      footer: {
        product: 'Продукт',
        company: 'Компания',
        resources: 'Ресурсы',
        legal: 'Правовая инф.',
        songs: 'Песни',
        teams: 'Команда',
        pricing: 'Цены',
        setlists: 'Сет-листы',
        about: 'О нас',
        blog: 'Блог',
        careers: 'Карьера',
        community: 'Сообщество',
        documentation: 'Документация',
        tutorials: 'Уроки',
        support: 'Поддержка',
        privacyPolicy: 'Политика конфиденциальности',
        terms: 'Условия',
        cookies: 'Файлы cookie'
      }
    },
    songs: {
      title: 'Библиотека Песен',
      search: 'Поиск песен, авторов...',
      tableTitle: 'Название',
      tableKey: 'Тон.',
      tableBpm: 'BPM',
      tableAuthor: 'Автор',
      tableAdded: 'Добавлено',
      openReader: 'Открыть',
      noResults: 'Результаты не найдены',
      loading: 'Загрузка...',
      loadMore: 'Показать еще',
      backToTop: 'Наверх',
      sortTitle: 'Сорт.: Название',
      sortBpm: 'Сорт.: BPM',
      sortKey: 'Сорт.: Тональность',
      sortRecent: 'Недавно добавленные',
      unknownArtist: 'Неизвестный исполнитель',
      removeFromFav: 'Удалить',
      addToFav: 'Сохранить',
    },
    songView: {
      added: 'Песня сохранена ♥',
      removed: 'Удалено из сохраненных песен',
      loading: 'Загрузка...',
      error: 'Не удалось загрузить данные песни',
      back: 'Назад',
      useFlats: 'b',
      transpose: 'Транспозиция',
      capoSub: 'Капо',
      fontSize: 'Размер',
      downloadTxt: 'Скачать TXT',
      requestEdit: 'Правка',
      chordsOnly: 'Аккорды',
      lyricsOnly: 'Слова',
      bothModes: 'Оба',
      noCapo: 'Без Capo',
      clear: 'Очистить',
      keyPrefix: 'Тоник:',
      playAs: 'Играть как:',
      keySavedAlert: 'Тональность сохранена',
      keyIsSaved: '✓ Сохранено',
      saveKey: 'Сохранить новую тональность',
      semitones: 'полутонов',
      reset: 'Сброс',
      flats: '♭ Бемоли',
      sharps: '♯ Диезы',
      signs: 'Знаки',
      noLyrics: 'Текст недоступен',
      linkCopied: 'Ссылка скопирована',
      linkCopyError: 'Не удалось скопировать ссылку',
      setlistTitle: 'Сет-лист',
      key: 'Тональность:',
      tempo: 'Темп:',
      addToSetlist: 'Добавить в сет-лист',
      download: 'Скачать',
      edit: 'Редактировать',
      copied: 'Скопировано',
      copyError: 'Ошибка при копировании',
      copyContent: 'Копировать песню',
      copyLink: 'Копировать ссылку'
    },
    songRequest: {
      title: 'Запрос песни',
      titleNew: 'Предложить новую песню',
      titleEdit: 'Редактировать песню',
      badgeNew: '✨ Предложение новой песни',
      badgeEdit: '✏️ Предложение изменений',
      modeQuick: '⚡ Быстрый запрос',
      modeFull: '🎼 Полные данные',
      quickHint: 'Укажите название песни, исполнителя или ссылку на YouTube / MP3. Наша команда найдет песню, подберет аккорды и добавит её!',
      quickTitlePlaceholder: 'Пример: Благослови Господь или Hillsong - Oceans',
      quickNotesPlaceholder: 'Вставьте ссылку на YouTube / MP3 или примечания (напр. "Просьба добавить в тональности G")...',
      needLogin: 'Пожалуйста, войдите, чтобы отправить запрос.',
      songDataLoadError: 'Не удалось загрузить данные песни.',
      titleHy: 'Название (Армянский)',
      titleLat: 'Название (Латиница)',
      titleEn: 'Название (Английский)',
      titleRu: 'Название (Русский)',
      artist: 'Исполнитель / Группа',
      songKey: 'Тональность',
      selectKeyPlaceholder: '-- Выберите тональность --',
      bpm: 'BPM (Темп)',
      tags: 'Теги',
      chords: 'Аккорды (в стандартном формате)',
      lyrics: 'Слова (без аккордов)',
      lyricsAndChordsSection: 'Аккорды и Слова',
      chordsPreview: 'Предпросмотр аккордов',
      preview: '👁️ Предпросмотр',
      edit: '✏️ Редактировать',
      message: 'Сообщение модератору (необязательно)',
      notesPlaceholder: 'Напишите дополнительные примечания для модераторов...',
      basicsSection: 'Основные данные',
      musicSection: 'Музыкальные детали',
      submit: 'Отправить',
      submitBtnNew: 'Отправить предложение',
      submitBtnEdit: 'Сохранить и отправить изменения',
      submitting: 'Отправка...',
      success: 'Запрос успешно отправлен!',
      submitError: 'Не удалось отправить запрос',
      networkError: 'Ошибка сети',
      backToSong: 'Вернуться к песни'
    },
    setlists: {
      heroTitle: 'Планы поклонения',
      heroSubtitle: 'Управляйте сет-листами, планируйте служения и делитесь с командой.',
      statTotalSets: 'Сет-листы',
      statTotalSongs: 'Всего песен',
      statTeamSets: 'Командные',
      tabAll: 'Все',
      tabPersonal: 'Личные',
      tabTeam: 'Командные',
      tabShared: 'Общие',
      sortNewest: 'Сначала новые',
      sortOldest: 'Сначала старые',
      sortName: 'По названию',
      sortItems: 'По кол-ву песен',
      noDate: 'Без даты',
      backToSetlists: 'Сет-листы',
      publicBadge: 'Публичный Сет-лист',
      liveMode: 'Режим Live',
      saveToAccount: 'Сохранить в мои сет-листы',
      copyLink: 'Скопировать ссылку',
      copied: 'Скопировано!',
      saving: 'Сохранение...',
      statItems: 'Элементы',
      statSongs: 'Песни',
      statSections: 'Разделы',
      statRequired: 'Обязательные',
      itemsTitle: 'Песни сет-листа',
      keyLabel: 'Тональность',
      required: 'Обязательно',
      section: 'Раздел',
      errorTitle: 'Сет-лист недоступен',
      invalidToken: 'Недействительная или отсутствующая ссылка.',
      allSetlists: 'Смотреть сет-листы',
      importedTag: 'Копия',
      loginPrompt: 'Пожалуйста, войдите, чтобы создавать сет-листы.',
      newSetlist: 'Новый Сет-лист',
      errorLoad: 'Не удалось загрузить сет-листы',
      colTitle: 'Название',
      colDate: 'Дата',
      colSongs: 'Песни',
      colType: 'Тип',
      loading: 'Загрузка...',
      empty: 'У вас нет сохраненных сет-листов',
      unknownDate: 'Неизвестно',
      songsCount: 'песен',
      typeShared: 'Общий',
      typePersonal: 'Личный',
      edit: 'Редактировать',
      errorFetch: 'Не удалось загрузить данные сет-листа',
      goBack: 'Назад',
      addSong: 'Добавить песню',
      closeSearch: 'Закрыть поиск',
      searchPlaceholder: 'Искать песню...',
      searchBtn: 'Найти',
      addBtn: 'Добавить',
      emptySetlist: 'Сет-лист пуст. Добавьте песни через поиск.',
      noKey: 'Нет',
      remove: 'Удалить',
      confirmRemove: 'Вы уверены, что хотите удалить?',
      errorOccurred: 'Произошла ошибка',
      searchResults: 'Результаты поиска',
      editSetlist: 'Редактировать сет-лист',
      nameField: 'Название',
      dateField: 'Дата / День',
      descField: 'Описание',
      cancelBtn: 'Отмена',
      saveBtn: 'Сохранить',
      savingBtn: 'Сохранение...',
      namePlaceholder: 'напр. Воскресное Богослужение',
      assignTeam: 'Привязать к команде (необязательно)',
      personalTeam: '-- Личный --',
      createBtn: 'Создать',
      creatingBtn: 'Создание...',
      deleteBtn: 'Удалить Сет-лист',
      confirmDelete: 'Вы уверены, что хотите удалить этот сет-лист? Это действие необратимо.',
      limitReached: 'Достигнут лимит сет-листов.',
      createFailed: 'Не удалось создать сет-лист.',
      networkError: 'Ошибка сети'
    },
    news: { title: 'Новости и Обновления' },
    teams: {
      hero: 'Руководите Командой с Уверенностью',
      badge: 'Для Лидеров Поклонения',
      subtitle: 'Всё необходимое для координации команды поклонения на одной платформе.',
      cta: 'Посмотреть Цены',
      ctaJoin: 'Начать Бесплатно',
      dashboard: 'В Панель Управления',
      featuresTitle: 'Всё, что нужно вашей команде',
      ctaTitle: 'Готовы снарядить команду?',
      ctaSub: 'Присоединяйтесь к тысячам команд прославления, которые уже используют Worship Platform.',
      newTeamNamePrompt: 'Название новой команды:',
      memberEmailPrompt: 'Email участника:',
      addedAlert: 'Добавлено',
      createNewTeamBtn: 'Создать новую команду',
      upgradeRequired: 'Требуется улучшение плана',
      cancelBtn: 'Отмена',
      seePlansBtn: 'Смотреть тарифы',
      noTeams: 'У вас еще нет команд.',
      membersCountLabel: 'участников',
      roles: ['Гитарист', 'Пианист', 'Барабанщик', 'Вокалист', 'Духовые'],
      featuresList: [
        { icon: '👥', title: 'Члены Команды', desc: 'Добавляйте музыкантов и вокалистов. Управляйте ролями и разрешениями.' },
        { icon: '📋', title: 'Общие Сет-листы', desc: 'Создавайте и делитесь сет-листами со всей командой в реальном времени.' },
        { icon: '🎵', title: 'Аккорды', desc: 'Предоставьте команде доступ к аккордам и текстам.' },
        { icon: '🔔', title: 'Уведомления о Репетициях', desc: 'Отправляйте автоматические напоминания о репетициях.' },
        { icon: '📊', title: 'Аналитика', desc: 'Смотрите, какие песни используются чаще всего, и отслеживайте активность.' },
        { icon: '💬', title: 'Командный Чат', desc: 'Общайтесь прямо на платформе. Дополнительные приложения не нужны.' }
      ],
      addMemberPrompt: 'Введите email нового участника:',
      confirmRemoveMember: 'Вы уверены, что хотите удалить этого участника?',
      confirmDeleteTeam: 'Вы уверены, что хотите полностью удалить эту команду?',
      teamDetails: 'Детали Команды',
      deleteTeamBtn: 'Удалить Команду',
      addMemberBtn: '+ Добавить Участника',
      teamMembersListTitle: 'Члены Команды',
      noMembers: 'В этой команде пока нет участников.'
    },
    favorites: {
      errorLoad: 'Не удалось загрузить сохраненные песни',
      loginTitle: 'Войти',
      loginPrompt: 'Пожалуйста, войдите, чтобы увидеть сохраненные песни.',
      loginBtn: 'Войти',
      title: 'Сохраненные песни',
      savedSongs: 'сохраненных песен',
      loading: 'Загрузка...',
      favoriteTag: 'Сохранено',
      playlist: 'Плейлист',
      confirmRemove: 'Удалить песню из сохраненных?',
      keyTag: 'Тональность:',
      openSong: 'Открыть Песню',
      noFavorites: 'У вас пока нет сохраненных песен.',
      emptyDesc: 'Сохраненные песни появятся здесь, чтобы вы могли быстро вернуться к ним.',
      openFirst: 'Открыть первую песню',
      browseSongs: 'Открыть песни',
      viewAll: 'Смотреть все',
      retry: 'Повторить',
      filterAll: 'Все',
      filterAndSort: 'Фильтр и сортировка',
      keyFilter: 'Тональность',
      resetFilters: 'Сбросить',
      applyFilters: 'Применить',
      sortLabel: 'Сортировка',
      sortSavedNewest: 'Недавно сохраненные',
      sortSavedOldest: 'Сначала сохраненные',
      sortTitle: 'Название А-Я',
      sortArtist: 'Исполнитель А-Я',
      sortKey: 'Тональность',
      sortBpmAsc: 'BPM по возрастанию',
      sortBpmDesc: 'BPM по убыванию',
      noFilterResults: 'По этому фильтру песни не найдены',
      noFilterResultsDesc: 'Попробуйте выбрать другую тональность или показать все сохраненные песни.',
      filterReset: 'Показать все'
    },
    notifications: {
      title: 'Уведомления',
      markAllRead: 'Отметить как прочитанные',
      loading: 'Загрузка...',
      newNotification: 'Новое уведомление',
      emptyTitle: 'Нет новых уведомлений',
      emptyDesc: 'Здесь будут появляться уведомления о вашей команде, сет-листах и других важных событиях.'
    },
    pricing: {
      badge: 'Простые Цены',
      title: 'Планы для Любой Команды',
      subtitle: 'Начните бесплатно. Переходите на следующий уровень по мере роста.',
      faqTitle: 'Часто Задаваемые Вопросы',
      popular: 'Популярный'
    },
    community: {
      title: 'Форум Сообщества',
      subtitle: 'Общайтесь с лидерами поклонения и музыкантами со всего мира.',
      trending: '🔥 Популярные Темы',
      resources: '📌 Ресурсы',
      browseLibrary: '🎵 Смотреть Библиотеку',
      createSetlist: '📋 Создать Сет-лист',
      latestNews: '📰 Последние Новости',
      replies: 'ответов',
      share: 'Поделиться'
    },
    resources: {
      title: 'Ресурсы',
      subtitle: 'Руководства, обучение и инструменты для вашей команды.',
      search: 'Поиск ресурсов…'
    },

    profile: {
      title: 'Профиль',
      desc: 'Управляйте своим аккаунтом и настройками.',
      currentPlan: 'Текущий план',
      loading: 'Загрузка...',
      upgradePlan: 'Сменить план',
      savedSongs: 'Сохраненные песни',
      myTeams: 'Мои команды',
      accountSettings: 'Настройки аккаунта',
      language: 'Язык',
      logout: 'Выйти',
      selectLanguage: 'Выберите язык',
      pushOn: 'Включено. Новые сообщения из чата будут приходить вовремя.',
      pushOff: 'Включите это, чтобы не пропускать новые сообщения из чата.',
      pushNote: 'Если уведомления отключены, вы не будете получать новые сообщения из чата. Для приложения это обязательно.',
      pushMissingManager: 'Произошла ошибка при включении уведомлений.',
      pushDisableConfirm: 'Если отключить уведомления, новые сообщения из чата не будут приходить. Вы уверены?',
      pushNotSupported: 'Ваше устройство или браузер не поддерживает push-уведомления. Убедитесь, что приложение добавлено на главный экран.',
      pushEnableError: 'Уведомления были отклонены или произошла ошибка.'
    },
    friends: {
      confirmRemove: 'Вы уверены?',
      tabs: {
        chats: 'Чаты',
        myFriends: 'Мои друзья',
        add: 'Добавить',
        requests: 'Запросы'
      },
      emptyFriends: 'У вас пока нет друзей. Перейдите во вкладку добавления, чтобы найти новых друзей.',
      chat: 'Чат',
      remove: 'Удалить',
      findTitle: 'Найти друзей',
      findDesc: 'Ищите пользователей по имени или email',
      searchPlaceholder: 'Введите имя или email...',
      alreadyFriends: 'Уже друзья (Чат)',
      cancelRequest: 'Отменить запрос',
      acceptRequest: 'Принять запрос',
      addFriend: '+ Добавить',
      searchEmpty: 'По запросу «{{query}}» ничего не найдено.',
      incomingTitle: 'Входящие запросы',
      outgoingTitle: 'Отправленные запросы',
      noIncoming: 'У вас нет новых запросов.',
      noOutgoing: 'У вас нет ожидающих отправленных запросов.',
      accept: 'Принять',
      reject: 'Отклонить',
      cancel: 'Отмена'
    },
    chat: {
      today: 'Сегодня',
      yesterday: 'Вчера',
      monthsGenitive: ['января', 'февраля', 'марта', 'апреля', 'мая', 'июня', 'июля', 'августа', 'сентября', 'октября', 'ноября', 'декабря'],
      deletedOrUnavailable: 'Этот чат был удален или недоступен.',
      group: 'Группа',
      offline: 'Не в сети',
      online: 'В сети',
      lastSeen: 'Был(а) в сети:',
      friendFallback: 'Друг',
      chatFallback: 'Чат',
      deleteTooltip: 'Удалить чат',
      loadingOlder: 'Загружаются старые сообщения...',
      emptyTitle: 'Начните разговор',
      emptySubtitle: 'Напишите первое сообщение здесь...',
      placeholder: 'Напишите сообщение...',
      sent: 'Отправлено',
      seen: 'Просмотрено',
      key: 'Тональность',
      open: 'Открыть',
      sharedSetlist: 'Поделился плейлистом',
      send: 'Отправить в Чат',
      deleteTitle: 'Удалить чат',
      deletePrompt: 'Как вы хотите удалить этот чат?',
      deleteMine: 'Удалить только у меня',
      deleteEveryone: 'Удалить у всех',
      cancel: 'Отмена'
    },
    call: {
      preparing: 'Подготовка микрофона...',
      calling: 'Вызов...',
      ringing: 'Входящий аудиозвонок',
      connecting: 'Подключение...',
      reconnecting: 'Восстановление связи...',
      ended: 'Звонок завершен',
      failed: 'Соединение прервано',
      accept: 'Принять',
      decline: 'Отклонить',
      end: 'Завершить',
      mute: 'Выключить микрофон',
      unmute: 'Включить микрофон',
      speakerOn: 'Громкая связь (Вкл)',
      speakerOff: 'Динамик (Выкл)',
      speaker: 'Громкая связь',
      retry: 'Повторить',
      close: 'Закрыть',
      minimize: 'Свернуть',
      expand: 'Открыть звонок',
      resumeAudio: 'Включить звук',
      audioOutput: 'Вывод звука',
      defaultOutput: 'Устройство по умолчанию',
      qualityGood: 'Хорошее соединение',
      qualityFair: 'Среднее соединение',
      qualityPoor: 'Слабое соединение',
      errors: {
        microphone_denied: 'Доступ к микрофону запрещен. Включите его в настройках устройства.',
        microphone_unsupported: 'Это устройство не поддерживает звонки с микрофоном.',
        microphone_failed: 'Не удалось включить микрофон.',
        microphone_lost: 'Соединение с микрофоном потеряно.',
        offline: 'Нет подключения к интернету. Ожидаем восстановления связи.',
        connection_failed: 'Не удалось восстановить звонок.',
        connection_unstable: 'Интернет-соединение нестабильно.',
        busy: 'Пользователь занят другим звонком.',
        rate_limited: 'Слишком много попыток вызова. Немного подождите.',
        invalid_target: 'Невозможно позвонить этому пользователю.',
        call_not_ringing: 'Этот звонок больше недоступен.',
        call_start_failed: 'Не удалось начать звонок.',
        default: 'Во время звонка произошла ошибка.'
      }
    },
    contact: {
      intro: 'Есть вопросы, предложения или хотите сотрудничать? Мы будем рады ответить вам.',
      docs: 'Документация',
      office: 'Офис',
      officeValue: 'Ереван, Армения',
      phone: 'Телефон',
      name: 'Имя',
      email: 'Email',
      message: 'Сообщение',
      yourName: 'Ваше имя',
      yourQuestion: 'Напишите ваш вопрос...',
      submit: 'Отправить',
      submitting: 'Отправка...',
      success: 'Спасибо. Ваше сообщение отправлено.',
      error: 'Что-то пошло не так. Пожалуйста, попробуйте еще раз.',
      networkError: 'Проблема с соединением. Проверьте подключение к интернету.'
    },
    newsState: {
      loading: 'Загрузка...',
      notFound: 'Новость не найдена',
      back: 'Назад',
      backToNews: '‹ Новости'
    },
    hub: {
      searchPlaceholder: 'Искать песни, артистов...',
      categories: {
        songs: 'Песни',
        artists: 'Артисты',
        setlists: 'Сетлисты',
        teams: 'Друзья',
        transposer: 'Транспонировать аккорды'
      },
      upcomingService: 'Предстоящее служение',
      startRehearsal: 'Начать репетицию',
      myFavorites: 'Сохраненные песни',
      recentChords: 'Недавно добавленные',
      latestNews: 'Новости сообщества'
    },

    transposer: {
      kicker: 'Музыкальный инструмент',
      title: 'Транспонирование аккордов',
      description: 'Введите или вставьте текст с аккордами и измените тональность, сохранив исходную структуру.',
      clear: 'Очистить',
      controls: 'Настройки транспонирования',
      shift: 'Сдвиг',
      down: 'Опустить на один полутон',
      up: 'Поднять на один полутон',
      resetShift: 'Вернуть исходную тональность',
      semitones: 'полутонов',
      notation: 'Обозначения',
      sharps: 'Диезы',
      flats: 'Бемоли',
      detectedKey: 'Первый аккорд',
      inputLabel: 'Исходные аккорды',
      inputHint: 'Строки и разделы сохраняются',
      placeholder: 'Куплет\nC | Am | F | G\n\nПрипев\nF | G | Em | Am',
      resultLabel: 'Результат',
      originalKey: 'Исходный вариант',
      copy: 'Копировать',
      copied: 'Скопировано',
      copyError: 'Не удалось скопировать результат.',
      empty: 'Введите аккорды, чтобы увидеть результат.'
    },

  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(localStorage.getItem('worship_lang') || 'am');

  useEffect(() => {
    localStorage.setItem('worship_lang', language);
    // Set html lang attribute
    document.documentElement.lang = language;
    
    // Sync language with backend
    fetch('/account_api.php?action=set_language', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ language })
    }).catch(console.error);
  }, [language]);

  const t = (key, fallbackText = null) => {
    const keys = key.split('.');
    let value = translations[language];
    for (const k of keys) {
      if (value && value[k] !== undefined) {
        value = value[k];
      } else {
        // Fallback: try English, then return fallbackText or key
        let fallback = translations['en'];
        for (const fk of keys) {
          if (fallback && fallback[fk] !== undefined) fallback = fallback[fk];
          else return (fallbackText !== null && typeof fallbackText === 'string') ? fallbackText : key;
        }
        return (typeof fallback === 'string' || Array.isArray(fallback) || (fallback && typeof fallback === 'object'))
          ? fallback
          : ((fallbackText !== null && typeof fallbackText === 'string') ? fallbackText : key);
      }
    }
    return (typeof value === 'string' || Array.isArray(value) || (value && typeof value === 'object'))
      ? value
      : ((fallbackText !== null && typeof fallbackText === 'string') ? fallbackText : key);
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, lang: language, setLang: setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
