import React, { createContext, useState, useContext, useEffect } from 'react';

const translations = {
  am: {
    auth: {
      loginTitle: 'Մուտք գործիր քո հաշվով',
      loginSubtitle: 'Մեկ միասնական մուտք քո անձնական գրադարանի, սեթլիստների և ծանուցումների համար՝ թե՛ կայքում, թե՛ ծրագրում։',
      back: 'Վերադառնալ',
      welcomeBack: 'Բարի վերադարձ',
      welcomeBackDesc: 'Մուտք գործիր, որպեսզի համաժամացնես քո պահպանված երգերը և սեթլիստները բոլոր սարքերում։',
      fillAllFields: 'Լրացրեք բոլոր դաշտերը',
      invalidLogin: 'Սխալ էլ. փոստ կամ գաղտնաբառ',
      invalidEmail: 'Մուտքագրեք վավեր էլ. փոստի հասցե',
      invalidUsernameSpaces: 'Մուտքանունը չի կարող բացատ պարունակել',
      networkError: 'Կապի խնդիր, խնդրում ենք փորձել կրկին:',
      saveLoginTitle: 'Պահպանե՞լ մուտքը այս սարքում',
      saveLoginDesc: 'Եթե պահպանեք մուտքը, այս սարքում նորից մուտք գործելու կարիք չի լինի, մինչև ինքներդ դուրս չգաք հաշվից։',
      saveLoginConfirm: 'Պահպանել մուտքը',
      saveLoginSkip: 'Ոչ հիմա',
      saveLoginError: 'Չհաջողվեց պահպանել մուտքը',
      loginOrEmail: 'Էլ. փոստ',
      password: 'Գաղտնաբառ',
      rememberMe: 'Հիշել ինձ',
      forgotPassword: 'Մոռացե՞լ եք',
      pleaseWait: 'Խնդրում ենք սպասել...',
      loginBtn: 'Մուտք',
      orContinue: 'կամ շարունակիր',
      googleLogin: 'Google-ով մուտք',
      googleReady: 'Պատրաստ է մուտքի համար',
      googleDisabled: 'Google մուտքը դեռ կարգավորված չէ։ Խնդրում ենք միացնել այն ադմինում։',
      googleDisabledShort: 'Դեռ կարգավորված չէ',
      noAccount: 'Չունե՞ս հաշիվ։',
      createNow: 'Ստեղծել հիմա',
      registerTitle: 'Ստեղծել հաշիվ',
      registerSubtitle: 'Միացիր պաշտամունքային թիմերին ամբողջ աշխարհից։ Պահպանիր քո երգերը և սեթլիստները բոլոր սարքերում։',
      joinCommunity: 'Միացիր մեր համայնքին',
      joinDesc: 'Ստեղծիր անվճար հաշիվ՝ քո անձնական գրադարանը և թիմերը կառավարելու համար։',
      fullName: 'Անուն Ազգանուն',
      username: 'Մուտքանուն',
      email: 'Էլ. հասցե',
      confirmPassword: 'Հաստատել գաղտնաբառը',
      passwordMismatch: 'Գաղտնաբառերը չեն համընկնում',
      registerBtn: 'Գրանցվել',
      hasAccount: 'Արդեն ունե՞ս հաշիվ։',
      loginNow: 'Մուտք գործել'
    },
    settings: {
      title: 'Կարգավորումներ',
      mobileMenu: 'Մենյու',
      tabs: {
        profile: 'Անձնական',
        app: 'Ծրագիր',
        security: 'Անվտանգություն',
        sessions: 'Սեսիաներ',
        requests: 'Հարցումներ',
        danger: 'Վտանգավոր'
      },
      app: {
        desc: 'Կարգավորեք ծրագրի արտաքին տեսքը և աշխատանքի պարամետրերը:',
        keepAwake: 'Միշտ արթուն էկրան',
        keepAwakeDesc: 'Երգերի բառերը կարդալիս էկրանը չի անջատվի։',
        reduceMotion: 'Պարզեցված անիմացիաներ',
        reduceMotionDesc: 'Անջատում է էջերի անցումների էֆեկտները ավելի արագ աշխատանքի համար։',
        oledMode: 'OLED Մութ ռեժիմ (Իրական սև)',
        oledModeDesc: 'Օգտագործում է բացարձակ սև գույնը (OLED էկրանների համար՝ մարտկոց խնայելու նպատակով)։',
        outlinedChords: 'Շրջանակված ակորդներ',
        outlinedChordsDesc: 'Ակորդները ցուցադրվում են որպես առանձին կոճակներ՝ ավելի հեշտ կարդալու համար։',
        chordColor: 'Ակորդների գույն',
        colorGold: 'Ոսկեգույն',
        colorBlue: 'Կապույտ',
        colorGreen: 'Կանաչ',
        colorRed: 'Կարմիր',
        enabled: 'Միացված է',
        disabled: 'Անջատված է',
        enable: 'Միացնել',
        disable: 'Անջատել',
        saved: 'Պահպանված է'
      },
      profile: {
        title: 'Անձնական տվյալներ',
        desc: 'Խմբագրեք Ձեր հիմնական տվյալները։',
        name: 'Անուն Ազգանուն',
        birthDate: 'Ծննդյան ամսաթիվ',
        gender: 'Սեռ',
        genderMale: 'Արական',
        genderFemale: 'Իգական',
        genderOther: 'Այլ',
        phone: 'Հեռախոս',
        save: 'Պահպանել',
        success: 'Տվյալները թարմացվել են'
      },
      security: {
        title: 'Անվտանգություն և Մուտք',
        desc: 'Կառավարեք Ձեր գաղտնաբառը և էլ. փոստի հասցեն։',
        emailStatus: 'Էլ. փոստի կարգավիճակ',
        unverified: 'Չհաստատված',
        verified: 'Հաստատված',
        sendVerify: 'Ուղարկել հաստատման նամակ',
        changeEmail: 'Փոխել էլ. հասցեն',
        newEmail: 'Նոր էլ. հասցե',
        saveEmail: 'Պահպանել էլ. հասցեն',
        changePassword: 'Փոխել գաղտնաբառը',
        oldPassword: 'Ընթացիկ գաղտնաբառ',
        newPassword: 'Նոր գաղտնաբառ',
        savePassword: 'Փոխել գաղտնաբառը',
        forgotPassword: 'Մոռացել եմ գաղտնաբառը',
        emailSent: 'Հաստատման հղումն ուղարկված է',
        passChanged: 'Գաղտնաբառը հաջողությամբ փոխվեց'
      },
      sessions: {
        title: 'Ակտիվ սեսիաներ',
        desc: 'Այստեղ երևում են սարքերը, որտեղ բացված է քո հաշիվը։',
        closeOther: 'Փակել մյուսները',
        currentDevice: 'Ընթացիկ սարք',
        remembered: 'Հիշված սարք',
        rememberTitle: 'Հիշել ինձ այս սարքում',
        rememberEnabled: 'Միացված է',
        rememberDisabled: 'Անջատված է',
        rememberDescOn: 'Այս սարքում մուտքը պահպանված է և կմնա ակտիվ մինչև դուրս գաք հաշվից։',
        rememberDescOff: 'Եթե միացնեք, այս սարքում մուտքը պահպանված կմնա մինչև դուրս գաք հաշվից։',
        rememberEnableBtn: 'Միացնել',
        rememberDisableBtn: 'Անջատել',
        rememberUpdatedOn: 'Հիշել ինձ-ը միացվեց',
        rememberUpdatedOff: 'Հիշել ինձ-ը անջատվեց',
        logout: 'Դուրս գալ',
        empty: 'Սեսիաներ չեն գտնվել:'
      },
      requests: {
        title: 'Իմ ուղարկած հարցումները',
        desc: 'Նոր երգերի ավելացման կամ գոյություն ունեցող երգերում խմբագրումների հարցումների կարգավիճակը։',
        type: 'Տեսակը',
        date: 'Ամսաթիվ',
        adminNote: 'Ադմինի արձագանք',
        empty: 'Դուք դեռ չունեք ուղարկված հարցումներ։'
      },
      danger: {
        title: 'Վտանգավոր գործողություն',
        desc: 'Օգտահաշվի ջնջումը անշրջելի է։ Կկորչեն պահպանած երգերը և ամբողջ տվյալները։',
        deleteBtn: 'Ջնջել օգտահաշիվը',
        modalTitle: 'Հաստատեք ջնջումը',
        modalDesc: 'Խնդրում ենք մուտքագրել Ձեր գաղտնաբառը՝ հաշիվը վերջնականապես ջնջելու համար։',
        password: 'Գաղտնաբառ',
        cancel: 'Չեղարկել',
        confirm: 'Հաստատել և Ջնջել'
      }
    },
    dashboard: {
      library: 'Երգարան',
      search: 'Որոնել երգ...',
      loginSetlists: 'Մուտք գործեք երգացանկեր...',
      manageSetlists: 'Կառավարել երգացանկերը',
      loginPrompt: 'Մուտք գործեք՝ երգացանկեր կազմելու համար',
      loginBtn: 'Մուտք',
      emptySetlist: 'Այս երգացանկում դեռ երգեր չկան:',
      key: 'Տոնայնություն:',
      openStageReader: 'Բացել Stage Reader',
      emptyTitle: 'Հոգով և սրտով, զորությամբ Քեզ կերգեմ',
      emptyVerse: 'Verse/Chorus',
      emptyBridge: 'Bridge'
    },
    nav: {
      home: 'Գլխավոր',
      songs: 'Երգեր',
      sets: 'Երգացանկեր',
      friends: 'Ընկերներ',
      community: 'Համայնք',
      pricing: 'Գներ',
      resources: 'Ռեսուրսներ',
      news: 'Նորություններ',
      login: 'Մուտք',
      register: 'Գրանցվել',
      logout: 'Դուրս գալ',
      search: 'Որոնել...',
      setlists: 'Երգացանկեր'
    },
    megaMenu: {
      features: 'Հնարավորություններ',
      music: 'Երաժշտություն',
      management: 'Կառավարում',
      latestArrival: 'Նորություններ',
      discoverSongs: 'Բացահայտեք նոր երգեր, ակորդներ և ստեղծեք երգացանկեր:',
      readArticle: 'Կարդալ ավելին »',
      communityDesc: 'Միացեք մեր համայնքին, կիսվեք փորձով և գտեք նոր ընկերներ:',
      joinNow: 'Միանալ հիմա »',
      materials: 'Նյութեր',
      info: 'Տեղեկատվություն',
      contacts: 'Կապ'
    },
    landing: {
      heroTitle1: 'Կազմակերպի՛ր',
      heroTitle2: 'Քո Պաշտամունքային Թիմը',
      heroSubtitle: 'Ծառայությունների պլանավորում, ակորդների հասանելիություն, ու թիմային համագործակցություն — մեկ հարթակում:',
      startBtn: 'Սկսել անվճար',
      watchDemo: 'Դիտել Demo',
      popularSongs: 'Հայտնի Երգեր',
      communityPicks: 'Համայնքի Ընտրություն',
      browse: 'Թերթել',
      browseSongs: 'Երգեր',
      browseArtists: 'Արտիստներ',
      browseCollections: 'Հավաքածուներ',
      browseByKey: 'Ըստ տոնայնության',
      browseByBPM: 'Ըստ տեմպի',
      heroSubtitle1: 'Ավելի խելացի',
      latestNews: 'Վերջին Նորություններ',
      footerRights: '© 2026 Worship Platform. Բոլոր իրավունքները պաշտպանված են:',
      unknownArtist: 'Անհայտ արտիստ',
      picks: [
        { title: 'Երախտագիտություն', artist: 'Բրենդոն Լեյք', meta: 'Երգացանկ 14 · 9380 դիտում' },
        { title: 'Գերեզմաններից Պարտեզներ', artist: 'Bethel Worship', meta: 'Երգացանկ 17 · 320 դիտում' },
        { title: 'Ճանապարհ Բացող', artist: 'Sinach', meta: 'Երգացանկ 22 · 15k դիտում' }
      ],
      newsItems: [
        { date: 'Ապր 12, 2024', title: 'Նոր Հնարավորություն՝ Դինամիկ Տոնայնություն:', desc: 'Այժմ կարող եք փոխել երգի տոնայնությունը մեկ քլիքով:' },
        { date: 'Ապր 28, 2024', title: 'Տիրապետեք Երգացանկերի Պլանավորմանը', desc: 'Բացահայտեք, թե ինչպես է մեր գործիքը օգնում պլանավորել ծառայությունը:' },
        { date: 'Մայ 18, 2024', title: 'Համագործակցեք Ձեր Թիմի Հետ', desc: 'Կիսվեք ակորդներով և նշումներով Ձեր թիմի յուրաքանչյուր անդամի հետ:' }
      ],
      footer: {
        product: 'Պրոդուկտ',
        company: 'Ընկերություն',
        resources: 'Ռեսուրսներ',
        legal: 'Իրավական',
        songs: 'Երգեր',
        teams: 'Թիմ',
        pricing: 'Գներ',
        setlists: 'Երգացանկեր',
        about: 'Մեր մասին',
        blog: 'Բլոգ',
        careers: 'Կարիերա',
        community: 'Համայնք',
        documentation: 'Փաստաթղթեր',
        tutorials: 'Ուսուցում',
        support: 'Աջակցություն',
        privacyPolicy: 'Գաղտնիության քաղաքականություն',
        terms: 'Պայմաններ',
        cookies: 'Քուքիներ'
      }
    },
    songs: {
      title: 'Երգարան',
      search: 'Որոնել երգեր, հեղինակներ...',
      tableTitle: 'Անվանում',
      tableKey: 'Տոն.',
      tableBpm: 'BPM',
      tableAuthor: 'Հեղինակ',
      tableAdded: 'Ավելացված',
      openReader: 'Բացել',
      noResults: 'Ոչ մի արդյունք չի գտնվել',
      loading: 'Բեռնվում է...',
      loadMore: 'Ավելին',
      sortTitle: 'Կարգ. Անուն',
      sortBpm: 'Կարգ. BPM',
      sortKey: 'Կարգ. Տոն.',
      sortRecent: 'Վերջին ավելացվածը',
      unknownArtist: 'Անհայտ արտիստ',
      removeFromFav: 'Հեռացնել',
      addToFav: 'Պահպանել',
    },
    songView: {
      added: 'Ավելացվեց նախընտրածներում ♥',
      removed: 'Հեռացվեց նախընտրածներից',
      loading: 'Բեռնվում է...',
      error: 'Չհաջողվեց բեռնել երգի տվյալները',
      back: 'Հետ գնալ',
      useFlats: 'b',
      transpose: 'Տոնայնություն',
      capoSub: 'Կապո',
      fontSize: 'Տառաչափ',
      downloadTxt: 'Ներբեռնել TXT',
      requestEdit: 'Խմբագրել',
      chordsOnly: 'Ակորդներ',
      lyricsOnly: 'Բառեր',
      bothModes: 'Երկուսն էլ',
      noCapo: 'Առանց Capo',
      clear: 'Ջնջել',
      keyPrefix: 'Տոն:',
      playAs: 'Նվագել որպես:',
      keySavedAlert: 'Տոնայնությունը պահպանվեց',
      keyIsSaved: '✓ Պահպանված է',
      saveKey: '💾 Պահպանել',
      semitones: 'կիսատոն',
      reset: 'Reset',
      flats: '♭ Flats',
      sharps: '♯ Sharps',
      signs: 'Նշաններ',
      signs: 'Նշաններ',
      noLyrics: 'Բառերը հասանելի չեն',
      linkCopied: 'Հղումը պատճենված է',
      linkCopyError: 'Չհաջողվեց պատճենել հղումը',
      setlistTitle: 'Երգացանկ',
      key: 'Տոնայնություն:',
      tempo: 'Տեմպ:',
      addToSetlist: 'Ավելացնել երգացանկում',
      download: 'Ներբեռնել',
      edit: 'Խմբագրել',
      copied: 'Պատճենված է',
      copyError: 'Սխալ պատճենման ժամանակ',
      copyContent: 'Պատճենել երգը',
      copyLink: 'Պատճենել հղումը'
    },
    songRequest: {
      title: 'Երգի հարցում',
      titleNew: 'Առաջարկել Նոր Երգ',
      titleEdit: 'Խմբագրել երգը',
      needLogin: 'Հարցում ուղարկելու համար նախ մուտք գործիր։',
      songDataLoadError: 'Չհաջողվեց բեռնել երգի տվյալները:',
      titleHy: 'Վերնագիր (Հայերեն)',
      titleLat: 'Վերնագիր (Լատինատառ)',
      titleEn: 'Վերնագիր (Անգլերեն)',
      titleRu: 'Վերնագիր (Ռուսերեն)',
      artist: 'Հեղինակ / Խումբ',
      songKey: 'Տոնայնություն (Օր. C, Dm)',
      bpm: 'BPM',
      tags: 'Թեգեր',
      chords: 'Ակորդներ (ստանդարտ ֆորմատով)',
      lyrics: 'Բառեր (առանց ակորդների)',
      message: 'Նշում մոդերատորին (ոչ պարտադիր)',
      basicsSection: 'Հիմնական Տվյալներ',
      musicSection: 'Երաժշտական Մանրամասներ',
      submit: 'Ուղարկել',
      submitting: 'Ուղարկվում է...',
      success: 'Հարցումը հաջողությամբ ուղարկվեց:',
      submitError: 'Չհաջողվեց ուղարկել հարցումը',
      networkError: 'Կապի խնդիր'
    },
    setlists: {
      loginPrompt: 'Խնդրում ենք մուտք գործել՝ երգացանկեր կազմելու համար։',
      newSetlist: 'Նոր Երգացանկ',
      errorLoad: 'Չհաջողվեց բեռնել երգացանկերը',
      colTitle: 'Անվանում',
      colDate: 'Ամսաթիվ',
      colSongs: 'Երգեր',
      colType: 'Տեսակ',
      loading: 'Բեռնվում է...',
      empty: 'Դուք չունեք պահպանված երգացանկեր',
      unknownDate: 'Անհայտ',
      songsCount: 'երգ',
      typeShared: 'Համատեղ',
      typePersonal: 'Անձնական',
      edit: 'Խմբագրել',
      errorFetch: 'Չհաջողվեց բեռնել երգացանկի տվյալները',
      goBack: 'Հետ գնալ',
      addSong: 'Ավելացնել երգ',
      closeSearch: 'Փակել փնտրումը',
      searchPlaceholder: 'Փնտրել երգ ավելացնելու համար...',
      searchBtn: 'Փնտրել',
      addBtn: 'Ավելացնել',
      emptySetlist: 'Երգացանկը դատարկ է։ Ավելացրեք երգեր փնտրման միջոցով։',
      noKey: 'Չկա',
      remove: 'Հեռացնել',
      confirmRemove: 'Համոզվա՞ծ եք, որ ուզում եք հեռացնել:',
      errorOccurred: 'Սխալ տեղի ունեցավ',
      searchResults: 'Որոնման արդյունքները',
      editSetlist: 'Խմբագրել երգացանկը',
      nameField: 'Անուն',
      dateField: 'Ամսաթիվ / Օր',
      descField: 'Նկարագրություն',
      cancelBtn: 'Չեղարկել',
      saveBtn: 'Պահպանել'
    },
    news: { 
      title: 'Նորություններ և Թարմացումներ'
    },
    teams: {
      hero: 'Ղեկավարի՛ր Քո Թիմը Վստահությամբ',
      badge: 'Պաշտամունքային Ղեկավարների համար',
      subtitle: 'Ամեն ինչ, ինչ անհրաժեշտ է քո պաշտամունքային թիմը համակարգելու համար՝ մեկ հզոր, հեշտ օգտագործվող հարթակում:',
      cta: 'Տեսնել Գները',
      ctaJoin: 'Սկսել Անվճար',
      dashboard: 'Գնալ Վահանակ',
      featuresTitle: 'Այն Ամենը, Ինչ Քո Թիմին Անհրաժեշտ Է',
      ctaTitle: 'Պատրա՞ստ ես զինել քո թիմը:',
      ctaSub: 'Միացիր հազարավոր պաշտամունքային թիմերին, ովքեր արդեն օգտագործում են Worship Platform-ը:',
      newTeamNamePrompt: 'Նոր թիմի անուն:',
      memberEmailPrompt: 'Մասնակցի էլ. հասցե:',
      addedAlert: 'Ավելացվեց',
      createNewTeamBtn: 'Ստեղծել նոր թիմ',
      upgradeRequired: 'Անհրաժեշտ է փաթեթի բարելավում',
      cancelBtn: 'Չեղարկել',
      seePlansBtn: 'Տեսնել Գները',
      noTeams: 'Դուք դեռ թիմեր չունեք:',
      membersCountLabel: 'անդամ',
      roles: ['Կիթառահար', 'Դաշնակահար', 'Թմբկահար', 'Վոկալիստ', 'Փողային'],
      featuresList: [
        { icon: '👥', title: 'Թիմի Անդամներ', desc: 'Ավելացրու երաժիշտներ և վոկալիստներ: Կառավարիր դերերն ու իրավունքները:' },
        { icon: '📋', title: 'Համատեղ Երգացանկեր', desc: 'Ստեղծիր և կիսվիր երգացանկերով թիմի հետ իրական ժամանակում:' },
        { icon: '🎵', title: 'Ակորդներ', desc: 'Տրամադրիր թիմին ակորդների և բառերի հասանելիություն:' },
        { icon: '🔔', title: 'Փորձերի Ծանուցումներ', desc: 'Ուղարկիր ավտոմատ հիշեցումներ փորձերի համար:' },
        { icon: '📊', title: 'Վիճակագրություն', desc: 'Տես, թե որ երգերն են ամենաշատը օգտագործվում և հետևիր ակտիվությանը:' },
        { icon: '💬', title: 'Թիմային Չաթ', desc: 'Շփվիր անմիջապես հարթակի ներսում: Նոր հավելվածներ պետք չեն:' }
      ],
      addMemberPrompt: 'Մուտքագրեք նոր անդամի էլ. հասցեն:',
      confirmRemoveMember: 'Համոզվա՞ծ եք:',
      confirmDeleteTeam: 'Համոզվա՞ծ եք, որ ուզում եք ջնջել այս թիմը:',
      teamDetails: 'Թիմի տվյալներ',
      deleteTeamBtn: 'Ջնջել Թիմը',
      addMemberBtn: '+ Ավելացնել Անդամ',
      teamMembersListTitle: 'Թիմի Անդամներ',
      noMembers: 'Այս թիմում դեռ անդամներ չկան:'
    },
    favorites: {
      errorLoad: 'Չհաջողվեց բեռնել ֆավորիտները',
      loginTitle: 'Մուտք գործեք',
      loginPrompt: 'Խնդրում ենք մուտք գործել՝ ձեր ֆավորիտ երգերը տեսնելու համար:',
      loginBtn: 'Մուտք',
      title: 'Իմ Ընտրանին',
      savedSongs: 'պահպանված երգեր',
      loading: 'Բեռնվում է...',
      favoriteTag: 'Ֆավորիտ',
      playlist: 'Պլեյլիստ',
      confirmRemove: 'Հեռացնե՞լ երգը պահպանվածներից:',
      keyTag: 'Տոնայնություն:',
      openSong: 'Բացել Երգը',
      noFavorites: 'Դեռ չունեք պահպանված երգեր:',
      emptyDesc: 'Պահպանված երգերը կհայտնվեն այստեղ, որպեսզի արագ վերադառնաք դրանց։',
      openFirst: 'Բացել առաջին երգը',
      browseSongs: 'Բացել երգարանը',
      retry: 'Կրկին փորձել',
      filterAll: 'Բոլորը',
      noFilterResults: 'Այս ֆիլտրով երգ չի գտնվել',
      noFilterResultsDesc: 'Փորձեք ընտրել այլ տոնայնություն կամ բացել բոլոր պահպանված երգերը։',
      filterReset: 'Ցույց տալ բոլորը'
    },
    notifications: {
      title: 'Ծանուցումներ',
      markAllRead: 'Նշել որպես կարդացված',
      loading: 'Բեռնվում է...',
      newNotification: 'Նոր ծանուցում',
      emptyTitle: 'Նոր ծանուցումներ չկան',
      emptyDesc: 'Այստեղ կհայտնվեն Ձեր թիմի, երգացանկերի և այլ կարևոր իրադարձությունների մասին ծանուցումները:'
    },
    pricing: {
      badge: 'Պարզ Գներ',
      title: 'Պլաններ Բոլոր Թիմերի Համար',
      subtitle: 'Սկսիր անվճար: Ընդլայնիր, երբ Քո ծառայությունն աճի:',
      faqTitle: 'Հաճախ Տրվող Հարցեր',
      popular: 'Ամենապահանջված'
    },
    community: {
      title: 'Համայնքային Ֆորում',
      subtitle: 'Կապ հաստատիր աշխարհի տարբեր երկրների պաշտամունքային ղեկավարների հետ:',
      trending: '🔥 Թրենդային Թեմաներ',
      resources: '📌 Ռեսուրսներ',
      browseLibrary: '🎵 Թերթել Երգարանը',
      createSetlist: '📋 Ստեղծել Երգացանկ',
      latestNews: '📰 Վերջին Նորությունները',
      replies: 'պատասխան',
      share: 'Կիսվել'
    },
    resources: {
      title: 'Ռեսուրսներ',
      subtitle: 'Ուղեցույցներ, ձեռնարկներ և գործիքներ քո թիմի հաջողության համար:',
      search: 'Որոնել ռեսուրսներ...'
    },

    profile: {
      title: 'Պրոֆիլ',
      desc: 'Կառավարեք Ձեր հաշիվը և նախընտրությունները:',
      currentPlan: 'Ընթացիկ փաթեթ',
      loading: 'Բեռնվում է...',
      upgradePlan: 'Փոխել փաթեթը',
      savedSongs: 'Պահպանված երգեր',
      myTeams: 'Իմ թիմերը',
      accountSettings: 'Կարգավորումներ',
      language: 'Լեզու',
      logout: 'Ելք',
      selectLanguage: 'Ընտրեք լեզուն',
      pushOn: 'Միացված է։ Չաթի նոր նամակները կստանաք ժամանակին։',
      pushOff: 'Միացրեք, որպեսզի չաթից նոր նամակները բաց չթողնեք։',
      pushNote: 'Եթե ծանուցումները միացված չեն, չաթից նոր նամակներ չեք ստանա։ Ծրագրի համար սա պարտադիր է։',
      pushMissingManager: 'Սխալ առաջացավ ծանուցումների ակտիվացման ժամանակ։',
      pushDisableConfirm: 'Եթե ծանուցումները անջատեք, չաթից նոր նամակներ չեք ստանա։ Վստա՞հ եք, որ ուզում եք անջատել։',
      pushNotSupported: 'Ձեր սարքը կամ բրաուզերը չի ապահովում Push ծանուցումներ: Համոզվեք, որ ծրագիրը ավելացրել եք հեռախոսի էկրանին։',
      pushEnableError: 'Ծանուցումները մերժվեցին կամ խնդիր առաջացավ։'
    },
    friends: {
      confirmRemove: 'Համոզվա՞ծ եք։',
      tabs: {
        chats: 'Չաթեր',
        myFriends: 'Իմ ընկերները',
        add: 'Ավելացնել',
        requests: 'Հարցումներ'
      },
      emptyFriends: 'Դուք դեռ ընկերներ չունեք: Անցեք «Ավելացնել» բաժին նոր ընկերներ գտնելու համար:',
      chat: 'Չաթ',
      remove: 'Հեռացնել',
      findTitle: 'Գտնել ընկերներ',
      findDesc: 'Որոնեք օգտատերերին ըստ անվան կամ էլ. փոստի',
      searchPlaceholder: 'Մուտքագրեք անուն կամ փոստ...',
      alreadyFriends: 'Ընկերներ եք (Չաթ)',
      cancelRequest: 'Չեղարկել հարցումը',
      acceptRequest: 'Ընդունել հարցումը',
      addFriend: '+ Ավելացնել',
      searchEmpty: 'Ոչինչ չգտնվեց «{{query}}» որոնմամբ:',
      incomingTitle: 'Ստացված հարցումներ',
      outgoingTitle: 'Ուղարկված հարցումներ',
      noIncoming: 'Դուք չունեք նոր հարցումներ:',
      noOutgoing: 'Դուք սպասվող ուղարկված հարցումներ չունեք:',
      accept: 'Ընդունել',
      reject: 'Մերժել',
      cancel: 'Չեղարկել'
    },
    chat: {
      today: 'Այսօր',
      yesterday: 'Երեկ',
      monthsGenitive: ['հունվարի', 'փետրվարի', 'մարտի', 'ապրիլի', 'մայիսի', 'հունիսի', 'հուլիսի', 'օգոստոսի', 'սեպտեմբերի', 'հոկտեմբերի', 'նոյեմբերի', 'դեկտեմբերի'],
      deletedOrUnavailable: 'Այս զրույցը ջնջվել է կամ հասանելի չէ:',
      group: 'Խումբ',
      offline: 'Անցանց',
      online: 'Առցանց',
      lastSeen: 'Վերջին անգամ՝',
      friendFallback: 'Ընկեր',
      chatFallback: 'Չաթ',
      deleteTooltip: 'Ջնջել զրույցը',
      loadingOlder: 'Ավելի հին հաղորդագրությունները բեռնվում են...',
      emptyTitle: 'Սկսեք զրույցը',
      emptySubtitle: 'Գրեք առաջին հաղորդագրությունը այստեղ...',
      placeholder: 'Գրեք հաղորդագրություն...',
      sent: 'Ուղարկված է',
      seen: 'Տեսել է',
      deleteTitle: 'Ջնջել զրույցը',
      deletePrompt: 'Ինչպե՞ս եք ցանկանում ջնջել այս զրույցը:',
      deleteMine: 'Ջնջել միայն ինձ համար',
      deleteEveryone: 'Ջնջել բոլորի համար',
      cancel: 'Չեղարկել'
    },
    contact: {
      intro: 'Ունե՞ք հարցեր, առաջարկներ կամ ցանկանում եք համագործակցել։ Մենք սիրով կպատասխանենք ձեզ:',
      docs: 'Փաստաթղթեր',
      office: 'Գրասենյակ',
      officeValue: 'Երևան, Հայաստան',
      phone: 'Հեռախոս',
      name: 'Անուն',
      email: 'Էլ. հասցե',
      message: 'Հաղորդագրություն',
      yourName: 'Ձեր անունը',
      yourQuestion: 'Գրեք ձեր հարցը...',
      submit: 'Ուղարկել',
      submitting: 'Ուղարկվում է...',
      success: 'Շնորհակալություն։ Ձեր հաղորդագրությունը ուղարկված է։',
      error: 'Սխալ տեղի ունեցավ: Խնդրում ենք փորձել կրկին:',
      networkError: 'Կապի խափանում: Խնդրում ենք ստուգել ինտերնետ կապը:'
    },
    newsState: {
      loading: 'Բեռնվում է...',
      notFound: 'Նորությունը չի գտնվել',
      back: 'Վերադառնալ',
      backToNews: '‹ Նորություններ'
    },
    hub: {
      searchPlaceholder: 'Որոնել երգեր, արտիստներ...',
      categories: {
        songs: 'Երգեր',
        artists: 'Արտիստներ',
        setlists: 'Երգացանկեր',
        teams: 'Ընկերներ'
      },
      upcomingService: 'Առաջիկա Ծառայություն',
      startRehearsal: 'Սկսել Փորձը',
      myFavorites: 'Իմ Սիրվածները',
      recentChords: 'Վերջին Ավելացվածները',
      latestNews: 'Համայնքի Նորություններ'
    },
    songRequest: {
      title: 'Առաջարկել Երգ'
    }
  },
  en: {
    auth: {
      loginTitle: 'Log in to your account',
      loginSubtitle: 'One unified login for your personal library, setlists, and notifications across web and app.',
      back: 'Go Back',
      welcomeBack: 'Welcome Back',
      welcomeBackDesc: 'Log in to sync your saved songs and setlists across all devices.',
      fillAllFields: 'Please fill out all fields',
      invalidLogin: 'Invalid email or password',
      invalidEmail: 'Enter a valid email address',
      invalidUsernameSpaces: 'Username cannot contain spaces',
      networkError: 'Network error, please try again.',
      saveLoginTitle: 'Save this login on this device?',
      saveLoginDesc: 'If you save it, you will stay signed in on this device until you log out yourself.',
      saveLoginConfirm: 'Save login',
      saveLoginSkip: 'Not now',
      saveLoginError: 'Could not save login',
      loginOrEmail: 'Email',
      password: 'Password',
      rememberMe: 'Remember me',
      forgotPassword: 'Forgot password?',
      pleaseWait: 'Please wait...',
      loginBtn: 'Log In',
      orContinue: 'or continue with',
      googleLogin: 'Log in with Google',
      googleReady: 'Ready to login',
      googleDisabled: 'Google sign-in is not configured yet. Please enable it in admin.',
      googleDisabledShort: 'Not configured yet',
      noAccount: 'Don\'t have an account?',
      createNow: 'Create now',
      registerTitle: 'Create an account',
      registerSubtitle: 'Join worship teams from around the world. Save your songs and setlists on all devices.',
      joinCommunity: 'Join our community',
      joinDesc: 'Create a free account to manage your personal library and teams.',
      fullName: 'Full Name',
      username: 'Username',
      email: 'Email address',
      confirmPassword: 'Confirm Password',
      passwordMismatch: 'Passwords do not match',
      registerBtn: 'Register',
      hasAccount: 'Already have an account?',
      loginNow: 'Log In'
    },
    settings: {
      title: 'Settings',
      mobileMenu: 'Menu',
      tabs: {
        profile: 'Profile',
        app: 'App',
        security: 'Security',
        sessions: 'Sessions',
        requests: 'Requests',
        danger: 'Danger Zone'
      },
      app: {
        desc: 'Adjust app appearance and operating parameters.',
        keepAwake: 'Keep Screen Awake',
        keepAwakeDesc: 'Screen will not turn off while reading song lyrics.',
        reduceMotion: 'Reduce Motion',
        reduceMotionDesc: 'Disables page transition effects for faster performance.',
        oledMode: 'OLED Dark Mode (True Black)',
        oledModeDesc: 'Uses absolute black background (saves battery on OLED screens).',
        outlinedChords: 'Outlined Chords',
        outlinedChordsDesc: 'Chords are displayed as individual buttons for easier reading.',
        chordColor: 'Chord Color',
        colorGold: 'Gold',
        colorBlue: 'Blue',
        colorGreen: 'Green',
        colorRed: 'Red',
        enabled: 'Enabled',
        disabled: 'Disabled',
        enable: 'Enable',
        disable: 'Disable',
        saved: 'Saved'
      },
      profile: {
        title: 'Personal Information',
        desc: 'Edit your basic details.',
        name: 'Full Name',
        birthDate: 'Birth Date',
        gender: 'Gender',
        genderMale: 'Male',
        genderFemale: 'Female',
        genderOther: 'Other',
        phone: 'Phone Number',
        save: 'Save Changes',
        success: 'Profile updated successfully'
      },
      security: {
        title: 'Security & Login',
        desc: 'Manage your password and email address.',
        emailStatus: 'Email Status',
        unverified: 'Unverified',
        verified: 'Verified',
        sendVerify: 'Send verification email',
        changeEmail: 'Change Email',
        newEmail: 'New Email Address',
        saveEmail: 'Save Email',
        changePassword: 'Change Password',
        oldPassword: 'Current Password',
        newPassword: 'New Password',
        savePassword: 'Update Password',
        forgotPassword: 'Forgot Password?',
        emailSent: 'Verification link sent',
        passChanged: 'Password changed successfully'
      },
      sessions: {
        title: 'Active Sessions',
        desc: 'Here you can see the devices where you are currently logged in.',
        closeOther: 'Close Others',
        currentDevice: 'Current Device',
        remembered: 'Remembered',
        rememberTitle: 'Remember me on this device',
        rememberEnabled: 'Enabled',
        rememberDisabled: 'Disabled',
        rememberDescOn: 'Your login is saved on this device and will stay active until you log out.',
        rememberDescOff: 'If you enable it, this device will stay signed in until you log out.',
        rememberEnableBtn: 'Enable',
        rememberDisableBtn: 'Disable',
        rememberUpdatedOn: 'Remember me enabled',
        rememberUpdatedOff: 'Remember me disabled',
        logout: 'Log Out',
        empty: 'No sessions found.'
      },
      requests: {
        title: 'My Requests',
        desc: 'Status of your new song or edit requests.',
        type: 'Type',
        date: 'Date',
        adminNote: 'Admin Response',
        empty: 'You have no sent requests yet.'
      },
      danger: {
        title: 'Danger Zone',
        desc: 'Account deletion is irreversible. All saved songs and data will be lost.',
        deleteBtn: 'Delete Account',
        modalTitle: 'Confirm Deletion',
        modalDesc: 'Please enter your password to permanently delete your account.',
        password: 'Password',
        cancel: 'Cancel',
        confirm: 'Confirm & Delete'
      }
    },
    dashboard: {
      library: 'Song Library',
      search: 'Search song...',
      loginSetlists: 'Access your setlists...',
      manageSetlists: 'Manage Setlists',
      loginPrompt: 'Log in to create setlists',
      loginBtn: 'Log In',
      emptySetlist: 'There are no songs in this setlist yet.',
      key: 'Key:',
      openStageReader: 'Open Stage Reader',
      emptyTitle: 'With all my heart and soul I will sing to You',
      emptyVerse: 'Verse/Chorus',
      emptyBridge: 'Bridge'
    },
    nav: {
      home: 'Home',
      songs: 'Songs',
      sets: 'Sets',
      friends: 'Friends',
      community: 'Community',
      pricing: 'Pricing',
      resources: 'Resources',
      news: 'News',
      login: 'Log In',
      register: 'Get Started',
      logout: 'Log Out',
      search: 'Search songs…',
      setlists: 'Setlists'
    },
    megaMenu: {
      features: 'Features',
      music: 'Music',
      management: 'Management',
      latestArrival: 'Latest Updates',
      discoverSongs: 'Discover new songs, chords, and build your setlists.',
      readArticle: 'Read more »',
      communityDesc: 'Join our community, share your experience and connect with others.',
      joinNow: 'Join now »',
      materials: 'Materials',
      info: 'Information',
      contacts: 'Contacts'
    },
    landing: {
      heroTitle1: 'Equip Your',
      heroTitle2: 'Worship Team',
      heroSubtitle: 'Streamline Service Planning, Access Modern Chords, and Collaborate Freely.',
      startBtn: 'Start for Free',
      watchDemo: 'Watch Demo',
      popularSongs: 'Popular Songs',
      communityPicks: 'Community Picks',
      browse: 'Browse',
      browseSongs: 'Songs',
      browseArtists: 'Artists',
      browseCollections: 'Collections',
      browseByKey: 'By Key',
      browseByBPM: 'By BPM',
      heroSubtitle1: 'Smarter',
      latestNews: 'Latest News',
      footerRights: '© 2026 Worship Platform. All rights reserved.',
      unknownArtist: 'Unknown Artist',
      picks: [
        { title: 'Gratitude', artist: 'Brandon Lake', meta: 'Sets 14 · Rev 1 · 9380 plays' },
        { title: 'Graves Into Gardens', artist: 'Bethel Worship', meta: 'Sets 17 · Rev 5 · 320 plays' },
        { title: 'Way Maker', artist: 'Sinach', meta: 'Sets 22 · Rev 2 · 15k plays' }
      ],
      newsItems: [
        { date: 'Apr 12, 2024', title: 'New Feature: Dynamic Transposition!', desc: 'Worship teams can now instantly transpose songs to any key with a single click.' },
        { date: 'Apr 28, 2024', title: 'Mastering Your Setlist Planning', desc: 'Discover how our setlist builder helps worship leaders plan more effectively.' },
        { date: 'May 18, 2024', title: 'Collaborate with Your Whole Team', desc: 'Share chords, notes, and rehearsal plans with every member of your worship team.' }
      ],
      footer: {
        product: 'Product',
        company: 'Company',
        resources: 'Resources',
        legal: 'Legal',
        songs: 'Songs',
        teams: 'Teams',
        pricing: 'Pricing',
        setlists: 'Setlists',
        about: 'About',
        blog: 'Blog',
        careers: 'Careers',
        community: 'Community',
        documentation: 'Documentation',
        tutorials: 'Tutorials',
        support: 'Support',
        privacyPolicy: 'Privacy Policy',
        terms: 'Terms',
        cookies: 'Cookies'
      }
    },
    songs: {
      title: 'Song Library',
      search: 'Search songs, artists...',
      tableTitle: 'Title',
      tableKey: 'Key',
      tableBpm: 'BPM',
      tableAuthor: 'Artist',
      tableAdded: 'Added',
      openReader: 'Open',
      noResults: 'No results found',
      loading: 'Loading...',
      loadMore: 'Load More',
      sortTitle: 'Sort: Title A–Z',
      sortBpm: 'Sort: BPM',
      sortKey: 'Sort: Key',
      sortRecent: 'Recently Added',
      unknownArtist: 'Unknown Artist',
      removeFromFav: 'Remove',
      addToFav: 'Save',
    },
    songView: {
      added: 'Added to Favorites ♥',
      removed: 'Removed from Favorites',
      loading: 'Loading...',
      error: 'Failed to fetch song',
      back: 'Go Back',
      useFlats: 'b',
      transpose: 'Transpose',
      capoSub: 'Capo',
      fontSize: 'Font',
      downloadTxt: 'Download TXT',
      requestEdit: 'Edit',
      chordsOnly: 'Chords',
      lyricsOnly: 'Lyrics',
      bothModes: 'Both',
      noCapo: 'No Capo',
      clear: 'Clear',
      keyPrefix: 'Key:',
      playAs: 'Play as:',
      keySavedAlert: 'Key saved',
      keyIsSaved: '✓ Saved',
      saveKey: '💾 Save',
      semitones: 'semitones',
      reset: 'Reset',
      flats: '♭ Flats',
      sharps: '♯ Sharps',
      signs: 'Signs',
      noLyrics: 'Lyrics are not available',
      linkCopied: 'Link copied',
      linkCopyError: 'Failed to copy link',
      setlistTitle: 'Setlist',
      key: 'Key:',
      tempo: 'Tempo:',
      addToSetlist: 'Add to Setlist',
      download: 'Download',
      edit: 'Edit',
      copied: 'Copied',
      copyError: 'Error copying',
      copyContent: 'Copy Song',
      copyLink: 'Copy Link'
    },
    songRequest: {
      title: 'Song Request',
      titleNew: 'Suggest New Song',
      titleEdit: 'Edit Song',
      needLogin: 'Please log in to submit a request.',
      songDataLoadError: 'Failed to load song data.',
      titleHy: 'Title (Armenian)',
      titleLat: 'Title (Latin)',
      titleEn: 'Title (English)',
      titleRu: 'Title (Russian)',
      artist: 'Artist / Band',
      songKey: 'Key (e.g. C, Dm)',
      bpm: 'BPM',
      tags: 'Tags',
      chords: 'Chords (standard format)',
      lyrics: 'Lyrics (without chords)',
      message: 'Message to moderator (optional)',
      basicsSection: 'Basic Information',
      musicSection: 'Music Details',
      submit: 'Submit Request',
      submitting: 'Submitting...',
      success: 'Request submitted successfully!',
      submitError: 'Failed to submit request',
      networkError: 'Network error'
    },
    setlists: {
      loginPrompt: 'Please log in to create and manage setlists.',
      newSetlist: 'New Setlist',
      errorLoad: 'Failed to load setlists',
      colTitle: 'Title',
      colDate: 'Date',
      colSongs: 'Songs',
      colType: 'Type',
      loading: 'Loading...',
      empty: 'You have no saved setlists',
      unknownDate: 'Unknown',
      songsCount: 'songs',
      typeShared: 'Shared',
      typePersonal: 'Personal',
      edit: 'Edit',
      errorFetch: 'Failed to fetch setlist data',
      goBack: 'Go Back',
      addSong: 'Add Song',
      closeSearch: 'Close Search',
      searchPlaceholder: 'Search song to add...',
      searchBtn: 'Search',
      addBtn: 'Add',
      emptySetlist: 'Setlist is empty. Add songs using search.',
      noKey: 'None',
      remove: 'Remove',
      confirmRemove: 'Are you sure you want to remove this?',
      errorOccurred: 'An error occurred',
      searchResults: 'Search Results',
      editSetlist: 'Edit Setlist',
      nameField: 'Name',
      dateField: 'Date / Day',
      descField: 'Description',
      cancelBtn: 'Cancel',
      saveBtn: 'Save'
    },
    news: { title: 'News & Updates' },
    teams: {
      hero: 'Lead Your Team With Confidence',
      badge: 'For Worship Leaders',
      subtitle: 'Everything you need to coordinate your worship team in one powerful, easy-to-use platform.',
      cta: 'See Plans & Pricing',
      ctaJoin: 'Start Free Trial',
      dashboard: 'Go to Dashboard',
      featuresTitle: 'Everything Your Team Needs',
      ctaTitle: 'Ready to Equip Your Team?',
      ctaSub: 'Join thousands of worship teams already using the Worship Platform.',
      newTeamNamePrompt: 'New Team Name:',
      memberEmailPrompt: 'Member Email:',
      addedAlert: 'Added',
      createNewTeamBtn: 'Create New Team',
      upgradeRequired: 'Upgrade Required',
      cancelBtn: 'Cancel',
      seePlansBtn: 'See Plans',
      noTeams: 'You have no teams yet.',
      membersCountLabel: 'members',
      roles: ['Guitarist', 'Pianist', 'Drummer', 'Vocalist', 'Brass'],
      featuresList: [
        { icon: '👥', title: 'Team Members', desc: 'Add musicians, vocalists, and tech team members. Assign roles and manage permissions.' },
        { icon: '📋', title: 'Shared Setlists', desc: 'Build and share setlists with your entire team. Everyone sees the same plan in real time.' },
        { icon: '🎵', title: 'Chord Sheets', desc: 'Give every team member access to chord charts, lyrics, and arrangement notes.' },
        { icon: '🔔', title: 'Rehearsal Alerts', desc: 'Send automatic reminders and schedule rehearsals so no one misses a practice.' },
        { icon: '📊', title: 'Analytics', desc: 'See which songs are used most, track team activity, and measure engagement.' },
        { icon: '💬', title: 'Team Chat', desc: 'Communicate directly inside the platform. No need for separate messaging apps.' }
      ],
      addMemberPrompt: 'Enter new member email:',
      confirmRemoveMember: 'Are you sure you want to remove this member?',
      confirmDeleteTeam: 'Are you sure you want to delete this team entirely?',
      teamDetails: 'Team Details',
      deleteTeamBtn: 'Delete Team',
      addMemberBtn: '+ Add Member',
      teamMembersListTitle: 'Team Members',
      noMembers: 'No members in this team yet.'
    },
    favorites: {
      errorLoad: 'Failed to load favorites',
      loginTitle: 'Log in',
      loginPrompt: 'Please log in to see your favorite songs.',
      loginBtn: 'Log in',
      title: 'My Favorites',
      savedSongs: 'saved songs',
      loading: 'Loading...',
      favoriteTag: 'Favorite',
      playlist: 'Playlist',
      confirmRemove: 'Remove this song from saved songs?',
      keyTag: 'Key:',
      openSong: 'Open Song',
      noFavorites: 'You have no saved songs yet.',
      emptyDesc: 'Saved songs will appear here so you can jump back to them quickly.',
      openFirst: 'Open first song',
      browseSongs: 'Browse songs',
      retry: 'Try again',
      filterAll: 'All',
      noFilterResults: 'No songs found for this filter',
      noFilterResultsDesc: 'Try another key or return to all saved songs.',
      filterReset: 'Show all'
    },
    notifications: {
      title: 'Notifications',
      markAllRead: 'Mark all as read',
      loading: 'Loading...',
      newNotification: 'New notification',
      emptyTitle: 'No new notifications',
      emptyDesc: 'Notifications about your team, setlists, and other important events will appear here.'
    },
    pricing: {
      badge: 'Simple Pricing',
      title: 'Plans for Every Team',
      subtitle: 'Start free. Upgrade as your ministry grows. Cancel anytime.',
      faqTitle: 'Frequently Asked Questions',
      popular: 'Most Popular'
    },
    community: {
      title: 'Community Forum',
      subtitle: 'Connect with worship leaders and musicians from around the world.',
      trending: '🔥 Trending Topics',
      resources: '📌 Resources',
      browseLibrary: '🎵 Browse Song Library',
      createSetlist: '📋 Create a Setlist',
      latestNews: '📰 Latest News',
      replies: 'replies',
      share: 'Share'
    },
    resources: {
      title: 'Resources',
      subtitle: 'Guides, tutorials, and tools to help your worship team thrive.',
      search: 'Search resources…'
    },

    profile: {
      title: 'Profile',
      desc: 'Manage your account and preferences.',
      currentPlan: 'Current Plan',
      loading: 'Loading...',
      upgradePlan: 'Upgrade Plan',
      savedSongs: 'Saved Songs',
      myTeams: 'My Teams',
      accountSettings: 'Account Settings',
      language: 'Language',
      logout: 'Logout',
      selectLanguage: 'Select Language',
      pushOn: 'Enabled. You will receive new chat messages on time.',
      pushOff: 'Turn this on so you do not miss new chat messages.',
      pushNote: 'If notifications are disabled, you will not receive new chat messages. This is required for the app.',
      pushMissingManager: 'An error occurred while enabling notifications.',
      pushDisableConfirm: 'If you disable notifications, you will not receive new chat messages. Are you sure?',
      pushNotSupported: 'Your device or browser does not support push notifications. Make sure the app is added to your home screen.',
      pushEnableError: 'Notifications were denied or an error occurred.'
    },
    friends: {
      confirmRemove: 'Are you sure?',
      tabs: {
        chats: 'Chats',
        myFriends: 'My Friends',
        add: 'Add',
        requests: 'Requests'
      },
      emptyFriends: 'You do not have friends yet. Go to the Add tab to find new friends.',
      chat: 'Chat',
      remove: 'Remove',
      findTitle: 'Find friends',
      findDesc: 'Search users by name or email',
      searchPlaceholder: 'Enter a name or email...',
      alreadyFriends: 'Already friends (Chat)',
      cancelRequest: 'Cancel request',
      acceptRequest: 'Accept request',
      addFriend: '+ Add',
      searchEmpty: 'Nothing found for “{{query}}”.',
      incomingTitle: 'Incoming requests',
      outgoingTitle: 'Sent requests',
      noIncoming: 'You have no new requests.',
      noOutgoing: 'You do not have pending sent requests.',
      accept: 'Accept',
      reject: 'Reject',
      cancel: 'Cancel'
    },
    chat: {
      today: 'Today',
      yesterday: 'Yesterday',
      monthsGenitive: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
      deletedOrUnavailable: 'This conversation was deleted or is unavailable.',
      group: 'Group',
      offline: 'Offline',
      online: 'Online',
      lastSeen: 'Last seen:',
      friendFallback: 'Friend',
      chatFallback: 'Chat',
      deleteTooltip: 'Delete conversation',
      loadingOlder: 'Loading older messages...',
      emptyTitle: 'Start the conversation',
      emptySubtitle: 'Write the first message here...',
      placeholder: 'Write a message...',
      sent: 'Sent',
      seen: 'Seen',
      deleteTitle: 'Delete conversation',
      deletePrompt: 'How would you like to delete this conversation?',
      deleteMine: 'Delete only for me',
      deleteEveryone: 'Delete for everyone',
      cancel: 'Cancel'
    },
    contact: {
      intro: 'Have questions, ideas, or want to collaborate? We would love to hear from you.',
      docs: 'Documentation',
      office: 'Office',
      officeValue: 'Yerevan, Armenia',
      phone: 'Phone',
      name: 'Name',
      email: 'Email',
      message: 'Message',
      yourName: 'Your name',
      yourQuestion: 'Write your question...',
      submit: 'Send',
      submitting: 'Sending...',
      success: 'Thank you. Your message has been sent.',
      error: 'Something went wrong. Please try again.',
      networkError: 'Connection problem. Please check your internet connection.'
    },
    newsState: {
      loading: 'Loading...',
      notFound: 'News article not found',
      back: 'Go back',
      backToNews: '‹ News'
    },
    hub: {
      searchPlaceholder: 'Search songs, artists...',
      categories: {
        songs: 'Songs',
        artists: 'Artists',
        setlists: 'Setlists',
        teams: 'Friends'
      },
      upcomingService: 'Upcoming Service',
      startRehearsal: 'Start Rehearsal',
      myFavorites: 'My Favorites',
      recentChords: 'Recently Added',
      latestNews: 'Community News'
    },

  },
  ru: {
    auth: {
      loginTitle: 'Войдите в свой аккаунт',
      loginSubtitle: 'Единый вход для вашей личной библиотеки, сет-листов и уведомлений на сайте и в приложении.',
      back: 'Назад',
      welcomeBack: 'С возвращением',
      welcomeBackDesc: 'Войдите, чтобы синхронизировать сохраненные песни и сет-листы на всех устройствах.',
      fillAllFields: 'Пожалуйста, заполните все поля',
      invalidLogin: 'Неверный email или пароль',
      invalidEmail: 'Введите корректный email адрес',
      invalidUsernameSpaces: 'Логин не может содержать пробелы',
      networkError: 'Ошибка сети, попробуйте еще раз.',
      saveLoginTitle: 'Сохранить вход на этом устройстве?',
      saveLoginDesc: 'Если сохранить вход, на этом устройстве не нужно будет входить снова, пока вы сами не выйдете из аккаунта.',
      saveLoginConfirm: 'Сохранить вход',
      saveLoginSkip: 'Не сейчас',
      saveLoginError: 'Не удалось сохранить вход',
      loginOrEmail: 'Email',
      password: 'Пароль',
      rememberMe: 'Запомнить меня',
      forgotPassword: 'Забыли пароль?',
      pleaseWait: 'Пожалуйста, подождите...',
      loginBtn: 'Войти',
      orContinue: 'или продолжите',
      googleLogin: 'Войти через Google',
      googleReady: 'Готово к входу',
      googleDisabled: 'Вход через Google еще не настроен. Включите его в админке.',
      googleDisabledShort: 'Еще не настроено',
      noAccount: 'Нет аккаунта?',
      createNow: 'Создать сейчас',
      registerTitle: 'Создать аккаунт',
      registerSubtitle: 'Присоединяйтесь к командам прославления со всего мира. Сохраняйте песни на всех устройствах.',
      joinCommunity: 'Присоединяйтесь к сообществу',
      joinDesc: 'Создайте бесплатный аккаунт для управления библиотекой и командами.',
      fullName: 'Имя Фамилия',
      username: 'Логин',
      email: 'Email адрес',
      confirmPassword: 'Подтвердите Пароль',
      passwordMismatch: 'Пароли не совпадают',
      registerBtn: 'Зарегистрироваться',
      hasAccount: 'Уже есть аккаунт?',
      loginNow: 'Войти'
    },
    settings: {
      title: 'Настройки',
      mobileMenu: 'Меню',
      tabs: {
        profile: 'Профиль',
        app: 'Приложение',
        security: 'Безопасность',
        sessions: 'Сессии',
        requests: 'Запросы',
        danger: 'Опасная зона'
      },
      app: {
        desc: 'Настройте внешний вид и параметры работы приложения.',
        keepAwake: 'Не выключать экран',
        keepAwakeDesc: 'Экран не погаснет при чтении текстов песен.',
        reduceMotion: 'Уменьшение движения',
        reduceMotionDesc: 'Отключает эффекты перехода страниц для более быстрой работы.',
        oledMode: 'Режим OLED (Истинный черный)',
        oledModeDesc: 'Использует абсолютно черный фон (экономит заряд на OLED экранах).',
        outlinedChords: 'Обведенные аккорды',
        outlinedChordsDesc: 'Аккорды отображаются в виде отдельных кнопок для удобства чтения.',
        chordColor: 'Цвет аккордов',
        colorGold: 'Золотой',
        colorBlue: 'Синий',
        colorGreen: 'Зеленый',
        colorRed: 'Красный',
        enabled: 'Включено',
        disabled: 'Отключено',
        enable: 'Включить',
        disable: 'Отключить',
        saved: 'Сохранено'
      },
      profile: {
        title: 'Личные данные',
        desc: 'Редактируйте свою основную информацию.',
        name: 'Имя Фамилия',
        birthDate: 'Дата рождения',
        gender: 'Пол',
        genderMale: 'Мужской',
        genderFemale: 'Женский',
        genderOther: 'Другое',
        phone: 'Телефон',
        save: 'Сохранить',
        success: 'Данные успешно обновлены'
      },
      security: {
        title: 'Безопасность и Вход',
        desc: 'Управление паролем и email адресом.',
        emailStatus: 'Статус Email',
        unverified: 'Не подтвержден',
        verified: 'Подтвержден',
        sendVerify: 'Отправить письмо',
        changeEmail: 'Изменить Email',
        newEmail: 'Новый Email',
        saveEmail: 'Сохранить Email',
        changePassword: 'Изменить пароль',
        oldPassword: 'Текущий пароль',
        newPassword: 'Новый пароль',
        savePassword: 'Обновить пароль',
        forgotPassword: 'Забыли пароль?',
        emailSent: 'Письмо отправлено',
        passChanged: 'Пароль успешно изменен'
      },
      sessions: {
        title: 'Активные сессии',
        desc: 'Здесь показаны устройства, на которых выполнен вход.',
        closeOther: 'Закрыть другие',
        currentDevice: 'Текущее устройство',
        remembered: 'Запомнено',
        rememberTitle: 'Запомнить меня на этом устройстве',
        rememberEnabled: 'Включено',
        rememberDisabled: 'Выключено',
        rememberDescOn: 'Вход сохранен на этом устройстве и останется активным, пока вы сами не выйдете.',
        rememberDescOff: 'Если включить, вход на этом устройстве сохранится до выхода из аккаунта.',
        rememberEnableBtn: 'Включить',
        rememberDisableBtn: 'Выключить',
        rememberUpdatedOn: 'Запомнить меня включено',
        rememberUpdatedOff: 'Запомнить меня выключено',
        logout: 'Выйти',
        empty: 'Сессий не найдено.'
      },
      requests: {
        title: 'Мои запросы',
        desc: 'Статус ваших запросов на добавление или изменение песен.',
        type: 'Тип',
        date: 'Дата',
        adminNote: 'Ответ админа',
        empty: 'У вас пока нет запросов.'
      },
      danger: {
        title: 'Опасная зона',
        desc: 'Удаление аккаунта необратимо. Все данные будут потеряны.',
        deleteBtn: 'Удалить аккаунт',
        modalTitle: 'Подтвердите удаление',
        modalDesc: 'Пожалуйста, введите пароль для удаления аккаунта.',
        password: 'Пароль',
        cancel: 'Отмена',
        confirm: 'Подтвердить и Удалить'
      }
    },
    dashboard: {
      library: 'Библиотека Песен',
      search: 'Поиск песни...',
      loginSetlists: 'Доступ к сет-листам...',
      manageSetlists: 'Управление сет-листами',
      loginPrompt: 'Войдите, чтобы создавать сет-листы',
      loginBtn: 'Войти',
      emptySetlist: 'В этом сет-листе пока нет песен.',
      key: 'Том:',
      openStageReader: 'Открыть Stage Reader',
      emptyTitle: 'Всем сердцем и душой буду петь Тебе',
      emptyVerse: 'Куплет/Припев',
      emptyBridge: 'Бридж'
    },
    nav: {
      home: 'Главная',
      songs: 'Песни',
      sets: 'Сет-листы',
      teams: 'Команда',
      community: 'Сообщество',
      pricing: 'Цены',
      resources: 'Ресурсы',
      news: 'Новости',
      login: 'Войти',
      register: 'Начать',
      logout: 'Выйти',
      search: 'Искать песни…',
      setlists: 'Сет-листы'
    },
    megaMenu: {
      features: 'Возможности',
      music: 'Музыка',
      management: 'Управление',
      latestArrival: 'Обновления',
      discoverSongs: 'Откройте для себя новые песни, аккорды и создавайте сет-листы.',
      readArticle: 'Читать далее »',
      communityDesc: 'Присоединяйтесь к нашему сообществу и делитесь опытом.',
      joinNow: 'Присоединиться »',
      materials: 'Материалы',
      info: 'Информация',
      contacts: 'Контакты'
    },
    landing: {
      heroTitle1: 'Снарядите',
      heroTitle2: 'Вашу Команду',
      heroSubtitle: 'Планирование служений, доступ к аккордам и командное сотрудничество — на одной платформе.',
      startBtn: 'Начать бесплатно',
      watchDemo: 'Смотреть Demo',
      popularSongs: 'Популярные Песни',
      communityPicks: 'Выбор сообщества',
      browse: 'Просмотр',
      browseSongs: 'Песни',
      browseArtists: 'Артисты',
      browseCollections: 'Коллекции',
      browseByKey: 'По тональности',
      browseByBPM: 'По темпу',
      heroSubtitle1: 'Умнее',
      latestNews: 'Последние Новости',
      footerRights: '© 2026 Worship Platform. Все права защищены.',
      unknownArtist: 'Неизвестный исполнитель',
      picks: [
        { title: 'Gratitude', artist: 'Brandon Lake', meta: 'Сет-листы 14 · 9380 просмптров' },
        { title: 'Graves Into Gardens', artist: 'Bethel Worship', meta: 'Сет-листы 17 · 320 просмотров' },
        { title: 'Way Maker', artist: 'Sinach', meta: 'Сет-листы 22 · 15k просмотров' }
      ],
      newsItems: [
        { date: 'Апр 12, 2024', title: 'Новая функция: Динамическая Тональность!', desc: 'Теперь команды могут транспонировать песни в один клик.' },
        { date: 'Апр 28, 2024', title: 'Мастер планирования', desc: 'Узнайте, как наш инструмент помогает планировать служение.' },
        { date: 'Май 18, 2024', title: 'Работайте вместе', desc: 'Делитесь аккордами и планами со всей командой.' }
      ],
      footer: {
        product: 'Продукт',
        company: 'Компания',
        resources: 'Ресурсы',
        legal: 'Правовая инф.',
        songs: 'Песни',
        teams: 'Команда',
        pricing: 'Цены',
        setlists: 'Сет-листы',
        about: 'О нас',
        blog: 'Блог',
        careers: 'Карьера',
        community: 'Сообщество',
        documentation: 'Документация',
        tutorials: 'Уроки',
        support: 'Поддержка',
        privacyPolicy: 'Политика конфиденциальности',
        terms: 'Условия',
        cookies: 'Файлы cookie'
      }
    },
    songs: {
      title: 'Библиотека Песен',
      search: 'Поиск песен, авторов...',
      tableTitle: 'Название',
      tableKey: 'Тон.',
      tableBpm: 'BPM',
      tableAuthor: 'Автор',
      tableAdded: 'Добавлено',
      openReader: 'Открыть',
      noResults: 'Результаты не найдены',
      loading: 'Загрузка...',
      loadMore: 'Показать еще',
      sortTitle: 'Сорт.: Название',
      sortBpm: 'Сорт.: BPM',
      sortKey: 'Сорт.: Тональность',
      sortRecent: 'Недавно добавленные',
      unknownArtist: 'Неизвестный исполнитель',
      removeFromFav: 'Удалить',
      addToFav: 'Сохранить',
    },
    songView: {
      added: 'Добавлено в избранное ♥',
      removed: 'Удалено из избранного',
      loading: 'Загрузка...',
      error: 'Не удалось загрузить данные песни',
      back: 'Назад',
      useFlats: 'b',
      transpose: 'Транспозиция',
      capoSub: 'Капо',
      fontSize: 'Размер',
      downloadTxt: 'Скачать TXT',
      requestEdit: 'Правка',
      chordsOnly: 'Аккорды',
      lyricsOnly: 'Слова',
      bothModes: 'Оба',
      noCapo: 'Без Capo',
      clear: 'Очистить',
      keyPrefix: 'Тоник:',
      playAs: 'Играть как:',
      keySavedAlert: 'Тональность сохранена',
      keyIsSaved: '✓ Сохранено',
      saveKey: '💾 Сохранить',
      semitones: 'полутонов',
      reset: 'Сброс',
      flats: '♭ Бемоли',
      sharps: '♯ Диезы',
      signs: 'Знаки',
      noLyrics: 'Текст недоступен',
      linkCopied: 'Ссылка скопирована',
      linkCopyError: 'Не удалось скопировать ссылку',
      setlistTitle: 'Сет-лист',
      key: 'Тональность:',
      tempo: 'Темп:',
      addToSetlist: 'Добавить в сет-лист',
      download: 'Скачать',
      edit: 'Редактировать',
      copied: 'Скопировано',
      copyError: 'Ошибка при копировании',
      copyContent: 'Копировать песню',
      copyLink: 'Копировать ссылку'
    },
    songRequest: {
      title: 'Запрос песни',
      titleNew: 'Предложить новую песню',
      titleEdit: 'Редактировать песню',
      needLogin: 'Пожалуйста, войдите, чтобы отправить запрос.',
      songDataLoadError: 'Не удалось загрузить данные песни.',
      titleHy: 'Название (Армянский)',
      titleLat: 'Название (Латиница)',
      titleEn: 'Название (Английский)',
      titleRu: 'Название (Русский)',
      artist: 'Исполнитель / Группа',
      songKey: 'Тональность (Напр. C, Dm)',
      bpm: 'BPM',
      tags: 'Теги',
      chords: 'Аккорды',
      lyrics: 'Слова',
      message: 'Сообщение модератору (необязательно)',
      basicsSection: 'Основные данные',
      musicSection: 'Музыкальные детали',
      submit: 'Отправить',
      submitting: 'Отправка...',
      success: 'Запрос успешно отправлен!',
      submitError: 'Не удалось отправить запрос',
      networkError: 'Ошибка сети'
    },
    setlists: {
      loginPrompt: 'Пожалуйста, войдите, чтобы создавать сет-листы.',
      newSetlist: 'Новый Сет-лист',
      errorLoad: 'Не удалось загрузить сет-листы',
      colTitle: 'Название',
      colDate: 'Дата',
      colSongs: 'Песни',
      colType: 'Тип',
      loading: 'Загрузка...',
      empty: 'У вас нет сохраненных сет-листов',
      unknownDate: 'Неизвестно',
      songsCount: 'песен',
      typeShared: 'Общий',
      typePersonal: 'Личный',
      edit: 'Редактировать',
      errorFetch: 'Не удалось загрузить данные сет-листа',
      goBack: 'Назад',
      addSong: 'Добавить песню',
      closeSearch: 'Закрыть поиск',
      searchPlaceholder: 'Искать песню...',
      searchBtn: 'Найти',
      addBtn: 'Добавить',
      emptySetlist: 'Сет-лист пуст. Добавьте песни через поиск.',
      noKey: 'Нет',
      remove: 'Удалить',
      confirmRemove: 'Вы уверены, что хотите удалить?',
      errorOccurred: 'Произошла ошибка',
      searchResults: 'Результаты поиска',
      editSetlist: 'Редактировать сет-лист',
      nameField: 'Название',
      dateField: 'Дата / День',
      descField: 'Описание',
      cancelBtn: 'Отмена',
      saveBtn: 'Сохранить'
    },
    news: { title: 'Новости и Обновления' },
    teams: {
      hero: 'Руководите Командой с Уверенностью',
      badge: 'Для Лидеров Поклонения',
      subtitle: 'Всё необходимое для координации команды поклонения на одной платформе.',
      cta: 'Посмотреть Цены',
      ctaJoin: 'Начать Бесплатно',
      dashboard: 'В Панель Управления',
      featuresTitle: 'Всё, что нужно вашей команде',
      ctaTitle: 'Готовы снарядить команду?',
      ctaSub: 'Присоединяйтесь к тысячам команд прославления, которые уже используют Worship Platform.',
      newTeamNamePrompt: 'Название новой команды:',
      memberEmailPrompt: 'Email участника:',
      addedAlert: 'Добавлено',
      createNewTeamBtn: 'Создать новую команду',
      upgradeRequired: 'Требуется улучшение плана',
      cancelBtn: 'Отмена',
      seePlansBtn: 'Смотреть тарифы',
      noTeams: 'У вас еще нет команд.',
      membersCountLabel: 'участников',
      roles: ['Гитарист', 'Пианист', 'Барабанщик', 'Вокалист', 'Духовые'],
      featuresList: [
        { icon: '👥', title: 'Члены Команды', desc: 'Добавляйте музыкантов и вокалистов. Управляйте ролями и разрешениями.' },
        { icon: '📋', title: 'Общие Сет-листы', desc: 'Создавайте и делитесь сет-листами со всей командой в реальном времени.' },
        { icon: '🎵', title: 'Аккорды', desc: 'Предоставьте команде доступ к аккордам и текстам.' },
        { icon: '🔔', title: 'Уведомления о Репетициях', desc: 'Отправляйте автоматические напоминания о репетициях.' },
        { icon: '📊', title: 'Аналитика', desc: 'Смотрите, какие песни используются чаще всего, и отслеживайте активность.' },
        { icon: '💬', title: 'Командный Чат', desc: 'Общайтесь прямо на платформе. Дополнительные приложения не нужны.' }
      ],
      addMemberPrompt: 'Введите email нового участника:',
      confirmRemoveMember: 'Вы уверены, что хотите удалить этого участника?',
      confirmDeleteTeam: 'Вы уверены, что хотите полностью удалить эту команду?',
      teamDetails: 'Детали Команды',
      deleteTeamBtn: 'Удалить Команду',
      addMemberBtn: '+ Добавить Участника',
      teamMembersListTitle: 'Члены Команды',
      noMembers: 'В этой команде пока нет участников.'
    },
    favorites: {
      errorLoad: 'Не удалось загрузить избранное',
      loginTitle: 'Войти',
      loginPrompt: 'Пожалуйста, войдите, чтобы увидеть ваши избранные песни.',
      loginBtn: 'Войти',
      title: 'Мое Избранное',
      savedSongs: 'сохраненных песен',
      loading: 'Загрузка...',
      favoriteTag: 'Избранное',
      playlist: 'Плейлист',
      confirmRemove: 'Удалить песню из сохраненных?',
      keyTag: 'Тональность:',
      openSong: 'Открыть Песню',
      noFavorites: 'У вас пока нет сохраненных песен.',
      emptyDesc: 'Сохраненные песни появятся здесь, чтобы вы могли быстро вернуться к ним.',
      openFirst: 'Открыть первую песню',
      browseSongs: 'Открыть песни',
      retry: 'Повторить',
      filterAll: 'Все',
      noFilterResults: 'По этому фильтру песни не найдены',
      noFilterResultsDesc: 'Попробуйте выбрать другую тональность или показать все сохраненные песни.',
      filterReset: 'Показать все'
    },
    notifications: {
      title: 'Уведомления',
      markAllRead: 'Отметить как прочитанные',
      loading: 'Загрузка...',
      newNotification: 'Новое уведомление',
      emptyTitle: 'Нет новых уведомлений',
      emptyDesc: 'Здесь будут появляться уведомления о вашей команде, сет-листах и других важных событиях.'
    },
    pricing: {
      badge: 'Простые Цены',
      title: 'Планы для Любой Команды',
      subtitle: 'Начните бесплатно. Переходите на следующий уровень по мере роста.',
      faqTitle: 'Часто Задаваемые Вопросы',
      popular: 'Популярный'
    },
    community: {
      title: 'Форум Сообщества',
      subtitle: 'Общайтесь с лидерами поклонения и музыкантами со всего мира.',
      trending: '🔥 Популярные Темы',
      resources: '📌 Ресурсы',
      browseLibrary: '🎵 Смотреть Библиотеку',
      createSetlist: '📋 Создать Сет-лист',
      latestNews: '📰 Последние Новости',
      replies: 'ответов',
      share: 'Поделиться'
    },
    resources: {
      title: 'Ресурсы',
      subtitle: 'Руководства, обучение и инструменты для вашей команды.',
      search: 'Поиск ресурсов…'
    },

    profile: {
      title: 'Профиль',
      desc: 'Управляйте своим аккаунтом и настройками.',
      currentPlan: 'Текущий план',
      loading: 'Загрузка...',
      upgradePlan: 'Сменить план',
      savedSongs: 'Сохраненные песни',
      myTeams: 'Мои команды',
      accountSettings: 'Настройки аккаунта',
      language: 'Язык',
      logout: 'Выйти',
      selectLanguage: 'Выберите язык',
      pushOn: 'Включено. Новые сообщения из чата будут приходить вовремя.',
      pushOff: 'Включите это, чтобы не пропускать новые сообщения из чата.',
      pushNote: 'Если уведомления отключены, вы не будете получать новые сообщения из чата. Для приложения это обязательно.',
      pushMissingManager: 'Произошла ошибка при включении уведомлений.',
      pushDisableConfirm: 'Если отключить уведомления, новые сообщения из чата не будут приходить. Вы уверены?',
      pushNotSupported: 'Ваше устройство или браузер не поддерживает push-уведомления. Убедитесь, что приложение добавлено на главный экран.',
      pushEnableError: 'Уведомления были отклонены или произошла ошибка.'
    },
    friends: {
      confirmRemove: 'Вы уверены?',
      tabs: {
        chats: 'Чаты',
        myFriends: 'Мои друзья',
        add: 'Добавить',
        requests: 'Запросы'
      },
      emptyFriends: 'У вас пока нет друзей. Перейдите во вкладку добавления, чтобы найти новых друзей.',
      chat: 'Чат',
      remove: 'Удалить',
      findTitle: 'Найти друзей',
      findDesc: 'Ищите пользователей по имени или email',
      searchPlaceholder: 'Введите имя или email...',
      alreadyFriends: 'Уже друзья (Чат)',
      cancelRequest: 'Отменить запрос',
      acceptRequest: 'Принять запрос',
      addFriend: '+ Добавить',
      searchEmpty: 'По запросу «{{query}}» ничего не найдено.',
      incomingTitle: 'Входящие запросы',
      outgoingTitle: 'Отправленные запросы',
      noIncoming: 'У вас нет новых запросов.',
      noOutgoing: 'У вас нет ожидающих отправленных запросов.',
      accept: 'Принять',
      reject: 'Отклонить',
      cancel: 'Отмена'
    },
    chat: {
      today: 'Сегодня',
      yesterday: 'Вчера',
      monthsGenitive: ['января', 'февраля', 'марта', 'апреля', 'мая', 'июня', 'июля', 'августа', 'сентября', 'октября', 'ноября', 'декабря'],
      deletedOrUnavailable: 'Этот чат был удален или недоступен.',
      group: 'Группа',
      offline: 'Не в сети',
      online: 'В сети',
      lastSeen: 'Был(а) в сети:',
      friendFallback: 'Друг',
      chatFallback: 'Чат',
      deleteTooltip: 'Удалить чат',
      loadingOlder: 'Загружаются старые сообщения...',
      emptyTitle: 'Начните разговор',
      emptySubtitle: 'Напишите первое сообщение здесь...',
      placeholder: 'Напишите сообщение...',
      sent: 'Отправлено',
      seen: 'Просмотрено',
      deleteTitle: 'Удалить чат',
      deletePrompt: 'Как вы хотите удалить этот чат?',
      deleteMine: 'Удалить только у меня',
      deleteEveryone: 'Удалить у всех',
      cancel: 'Отмена'
    },
    contact: {
      intro: 'Есть вопросы, предложения или хотите сотрудничать? Мы будем рады ответить вам.',
      docs: 'Документация',
      office: 'Офис',
      officeValue: 'Ереван, Армения',
      phone: 'Телефон',
      name: 'Имя',
      email: 'Email',
      message: 'Сообщение',
      yourName: 'Ваше имя',
      yourQuestion: 'Напишите ваш вопрос...',
      submit: 'Отправить',
      submitting: 'Отправка...',
      success: 'Спасибо. Ваше сообщение отправлено.',
      error: 'Что-то пошло не так. Пожалуйста, попробуйте еще раз.',
      networkError: 'Проблема с соединением. Проверьте подключение к интернету.'
    },
    newsState: {
      loading: 'Загрузка...',
      notFound: 'Новость не найдена',
      back: 'Назад',
      backToNews: '‹ Новости'
    },
    hub: {
      searchPlaceholder: 'Искать песни, артистов...',
      categories: {
        songs: 'Песни',
        artists: 'Артисты',
        setlists: 'Сетлисты',
        teams: 'Друзья'
      },
      upcomingService: 'Предстоящее служение',
      startRehearsal: 'Начать репетицию',
      myFavorites: 'Мои избранные',
      recentChords: 'Недавно добавленные',
      latestNews: 'Новости сообщества'
    },

  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(localStorage.getItem('worship_lang') || 'am');

  useEffect(() => {
    localStorage.setItem('worship_lang', language);
    // Set html lang attribute
    document.documentElement.lang = language;
    
    // Sync language with backend
    fetch('/account_api.php?action=set_language', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ language })
    }).catch(console.error);
  }, [language]);

  const t = (key) => {
    const keys = key.split('.');
    let value = translations[language];
    for (const k of keys) {
      if (value && value[k] !== undefined) {
        value = value[k];
      } else {
        // Fallback: try English, then return key
        let fallback = translations['en'];
        for (const fk of keys) {
          if (fallback && fallback[fk] !== undefined) fallback = fallback[fk];
          else return key;
        }
        return typeof fallback === 'string' || typeof fallback === 'object' ? fallback : key;
      }
    }
    return typeof value === 'string' || typeof value === 'object' ? value : key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, lang: language, setLang: setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
